### ISSUE TITLE
On Community page, replace Reddit /r/bitcoin link by a "multireddit" link

### ISSUE THREAD

**Issue by carnesen** [bitcoin-dot-org/bitcoin.org#1015]
Currently the [bitcoin.org community page](https://bitcoin.org/en/community) links to /r/Bitcoin on Reddit. In light of the fact that a significant part of the Bitcoin-related discussion there has been forced to move to other subreddits, it would be prudent to replace the /r/bitcoin link with a "multireddit" link:

[http://reddit.com/r/Bitcoin/](http://reddit.com/r/Bitcoin/) --> [https://reddit.com/r/Bitcoin+bitcoin_uncensored](https://reddit.com/r/Bitcoin+bitcoin_uncensored)

with an updated link description "Reddit's Bitcoin communities".

EDIT 8/21: Removed BitcoinXT from the proposed multireddit link in accordance with the [bitcoin.org hard fork policy](https://bitcoin.org/en/posts/hard-fork-policy) as per feedback below.

EDIT 8/22: Removed r/BTC due to low quality of posts.

**Comment by saivann** [comment]
While I personally don't think censoring discussions on a forum is an appropriate solution, and I think it may actually even benefit XT, I understand the fear and risk that represent a fork, and the danger that comes with the increasing division and exhaustion of developers on each side of that debate.

bitcoin.org is likely not the right place to fix the reddit issue as it has already [taken a position](https://bitcoin.org/en/posts/hard-fork-policy) on the subject and although bitcoin.org has focused more on Bitcoin in general in the last years, it is still the main website for Bitcoin Core.

Note; I will likely not comment more on that issue as everything that touches the block side debate on this repository usually turns out to be huge time blow with few work done.

**Comment by harding** [comment]
Since the removal of discussion on /r/bitcoin regarding XT and its particular hard forking rules, I think the quality of conversation and the front-page posts on the subreddit have significantly improved.  That this could only be achieved by removing some posts and banning some people is sad, but I don't see how it could've been accomplished otherwise.

I think we should continue linking to /r/bitcoin by itself as one of the Bitcoin community's most important discussion forums.  A link to /r/bitcoinxt is not appropriate for this site so long as the software that subreddit promotes contains hard forking code.  Links to other subreddits are always welcome for consideration, but I think they should be considered purely on the merit of their content rather than their moderation policies.

As @saivann says, discussion on this issue tracker about XT, hard forks, and the block size typically turns out to be a huge waste of time for everyone involved, so I'll follow Saïvann's lead and try to avoid commenting further on this issue.

**Comment by carnesen** [comment]
Thanks for the feedback. For the record, personally I don't support contentious hard forks either. That was not my intent here. I've removed BitcoinXT from the proposed multireddit link.
