### ISSUE TITLE
Palestra com Rocelo Lopes: Bitcoin

### ISSUE THREAD

**Issue by samuelhei** [bitcoin-dot-org/bitcoin.org#1067]
- date: 2015-09-25
      title: "Palestra com Rocelo Lopes: Bitcoin"
      venue: "IFC Camboriú"
      address: "Rua Joaquim Garcia, s/n - Centro"
      city: "Camboriú"
      country: "Brazil"
      link: "https://www.facebook.com/events/926407880754561/"

**Comment by wilbns** [comment]
@samuelhei Hello, I'm sorry we couldn't get this up on Bitcoin.org in time for your event. We usually try to update events 1-2 times a month. Since your date was only 4 days away in the future, it did not make it into our most recent update in the aforementioned interval.

I hope your event went well and everyone had a good time! :)
