### ISSUE TITLE
Fraud/Extortion

### ISSUE THREAD

**Issue by mattT1978** [bitcoin-dot-org/bitcoin.org#1069]
The following bitcoin address is being used to extort money from people in the wake of the Ashley Madison hacking.  I can forward the email that I got if needed.

1JeDGwyWQpuQZE6mfj2M7M1BWuAoLG4tE3

**Comment by saivann** [comment]
@mattT1978 You should probably contact the police with all details. It's probably also a good idea to mark the email as SPAM to reduce the efficacy of this fear campaign in the near future, potentially helping to bringing it to a halt.

Otherwise, I think there's nothing I, or anybody, can do about this. I am closing this issue as this GitHub repository is for work on bitcoin.org (the website), you may want to discuss what's happening with the communities https://bitcoin.org/en/community .

For the record, I've received a few emails reporting similar blackmailing over the last few days.
