### ISSUE TITLE
Bitcoin bank listings

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#1109]
We currently list Bitcoin banks as wallets.  I know that there is some concern over the term "bank" implying some degree of trust or regulation which may not apply to the concept of a "Bitcoin bank" but I propose for this discussion that the term "Bitcoin Bank" simply implies third party control of funds.

I don't believe that our current wallet criteria https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md#wallets provides (me at least) enough guidance to be able to recommend a Bitcoin bank alongside other Bitcoin wallets in the same categories.  I see this as similar to recommending home fire safes in the same category as national banks for the storage of funds; they're just not the same thing.  I would like to hear what others think about whether apps that are used for third party control should be recommended with wallets, separately, or not at all.  Do you think that our current criteria adequately covers Bitcoin banks?

In the meantime, I'll be having Bitcoin bank listing PRs tagged with a "Help Needed" label to indicate that we are looking for a volunteer, or volunteers to perform these reviews, at least until some other resolution can be found.

Current PRs which may fall into this category are #737, #832, #1056, and #1088.

**Comment by Ninkip2p** [comment]
Yes, I think "bank" is the wrong word, but there should be a clear definition regarding custody of the funds and responsibilities.

I propose they should be separated into "Wallets" and "Custodial Services" with clear descriptions of the implications of each

Normally custodial services double-up as ways of buying Bitcoins so I would also flag if purchasing bitcoin is possible via the service, established services such as Coinbase are a way to introduce new people to Bitcoin with a familiar user experience and easy way to purchase, which is what a lot of noobs are looking for.

The Custodial Services section could subdivide into web, mobile etc. (similar to the wallets section)

*Any wallet purporting to be non-custodial without open-sourcing code should be ignored. These wallets are shirking responsibilities on both ends by not taking on custodial responsibility and at the same time refusing to offer proof that they are non-custodial (presumably to protect their IP)

**Comment by crwatkins** [comment]
Since we haven't found anyone to review banks/custodial services nor have we had any refinements on our listing criteria, I have another proposal for consideration.  In agreement with @Ninkip2p I propose we create a separate listing category for banks (or whatever term we settle on).  There we would post listings with similar review and diligence as we now do for events (i.e. not much) as long as the listing meets some very basic criteria for legitimacy.  We would of course include a sufficient explanation of the listing criteria (a.k.a. "warning").

**Comment by ABISprotocol** [comment]
Well, this is an interesting discussion... 

Here's a concrete example:

Currently on bitcoin.org, we see at
https://bitcoin.org/en/choose-your-wallet
various options to "Choose your wallet."
However, if you click on the "web" button,
you see Coinbase as an option.  I don't consider that Coinbase is even a wallet actually,
it's a brokerage (one that is accessible through a website).
For reference, see:
https://github.com/btcfoundationedcom/btcfoundationedcom.github.io/blob/master/guides/en/buying.md

There's also an issue pending related to this matter here:  #996 
Quite unresolved, IMHO.  But clear definitions would go a long way (and we shouldn't even call Coinbase a wallet).

**Comment by Polve** [comment]
Yes, please remove Coinbase from the list of wallets

**Comment by skyjam** [comment]
Well it should be considered a wallet if it does 3 basic things, store tokens, and give the ability to send and receive those tokens. Now some wallets offer additional "features" including in the case of Coinbase the option to buy tokens. 

Its probable better to add a category related to buying bitcoins and adding services that offer this service to that than removing Apps that do offer wallet services.

**Comment by ABISprotocol** [comment]
Hello, per @crwatkins ~ I propose making categories - at minimum, as follows, for things that are actually not wallets:
CATEGORIES
1) banks
2) brokerages
2.a) brokerages that offer a wallet, or wallets in order to access the brokerage's service (example of this is Coinbase)
3) exchanges, centralized (bitstamp, btc-e, etc)
3.a) exchanges, decentralized (BitSquare, ExchangeD.I2P, etc.)

Once we figure out and agree on categories for bitcoin bank listings as per this issue with some more discussion, then there could be a PR for it relating to this issue.

After that step, I suggest then taking the additional step of reviewing the following:
https://github.com/bitcoin-dot-org/bitcoin.org/issues/996#issuecomment-143164573
and evaluating the terms being discussed there to determine how best to craft a PR in that additional issue.

cc:  @harding @Cobra-Bitcoin

**Comment by ABISprotocol** [comment]
See https://github.com/bitcoin-dot-org/bitcoin.org/pull/1223 which takes the first step proposed from my prior comment. @crwatkins @harding

**Comment by crwatkins** [comment]
After careful consideration, I continue to support my own proposal above https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702 to create a single separate category with the criteria listed.

**Comment by wbnns** [comment]
In an effort to resolve this issue, what are thoughts on creating a section called "Exchanges" on the resources page, and listing companies there:

![image](https://cloud.githubusercontent.com/assets/1130872/21287404/52ac0f10-c430-11e6-801f-add8b8d80060.png)

As part of this, we could then link Step 3 on the [Getting Started](https://bitcoin.org/en/getting-started) page to this section and keep people on-site (as opposed to sending them off Bitcoin.org to another website). We could modify the text in that section and include a disclaimer with some cautionary language regarding selecting an exchange that will provide you with a custodial account.

![image](https://cloud.githubusercontent.com/assets/1130872/21287411/7dba36be-c430-11e6-9df3-09398fb62c02.png)

Exchanges are an important part of the ecosystem, enabling more and more people to switch from their local currencies into bitcoin. This will allow us to link to them along with a disclaimer, and keep them separated from the wallets page.

**Comment by crwatkins** [comment]
I believe that would cover my [goals](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-162143702):  ACK.

**Comment by crwatkins** [comment]
I further would recommend that we move wallets scored with 
```
control: "checkfailcontrolthirdparty"
```
to the new exchanges category.  That would currently include Coinbase, Xapo, and Coinapult, as well as the (currently five) "third party" wallets requesting listing in open PRs.

Upon closer review and input from the community and the developers, it may turn out that some of these are not best categorized as exchanges (for reasons that they don't actually exchange currencies or that they also provide non-custodial wallet services) and we should deal with those on a case-by-case basis.

**Comment by wbnns** [comment]
An update - I realized that there are too many exchanges to put in a small section on the resources page, so I'm working on this:

![image](https://cloud.githubusercontent.com/assets/1130872/21584782/37d230aa-d076-11e6-9119-246a2374851a.png)

We could move custodial wallets that provide exchange services from the wallets page to this page, and also determine how we would like to handle the inclusion of custodial wallets that do not provide exchange services on a case-by-case basis, as @crwatkins mentioned.

**Since many people from all over the world arrive on Bitcoin.org wanting to learn more about Bitcoin and how to get started using it, this page will help them find places they can go to in order to acquire some.**

**This page will also allow us to have an opportunity to focus the wallets page on products that allow people to maintain full control over their funds.**
