### ISSUE TITLE
Create template for developer weekly IRC meetings

### ISSUE THREAD

**Issue by btcdrak** [bitcoin-dot-org/bitcoin.org#1147]
@G1lius have been kindly writing summaries of the weekly IRC dev meetings and posting them to various subreddits and the mailing list to help assist general users be aware of what Bitcoin Core developers are working on.

[example](https://www.reddit.com/r/Bitcoin/comments/3tyfaa/bitcoin_dev_irc_meeting_in_laymans_terms_20151119/)

I suggested to @harding we could create a place on bitcoin.org where @G1lius could submit a PR and have them published on bitcoin.org.

I'm opening this issue so it can be tracked.

**Comment by harding** [comment]
The version of Jekyll we use to build the site only supports one blog, which we currently use for site news.  The newest version supports multiple blogs, and I already have an patch that @saivann and I have played around with to upgrade us to that version.  It's a fairly big change, so I'll try to PR that individually in the next few days; once it looks like that's going to be merged, I'll work on creating a section for the weekly meeting notes and maybe other similar info.

@btcdrak good suggestion, thanks!  @G1lius thanks for making the notes, I've enjoyed reading them!

**Comment by btcdrak** [comment]
Closing. See https://github.com/bitcoin-core/website/issues/18#issuecomment-171316814

**Comment by harding** [comment]
Reopening.  I continue to think @G1lius's meeting summaries would make a good addition to Bitcoin.org and I just recently in PR #1193 provided the necessary changes to begin support hosting them.

**Comment by luke-jr** [comment]
ACK reopening. The meetings *are not* specifically about Bitcoin Core.

**Comment by btcdrak** [comment]
I am agnostic toward reopening the ticket but @luke-jr's statement is not accurate. Every IRC meeting is is attended by contributors to Bitcoin Core where the meeting topics cover Bitcoin Core pull-requests, issues and release schedules as all the previous meeting notes will corroborate. While the meetings are open, they are very much about the Bitcoin Core project's ongoing work.

**Comment by harding** [comment]
I (like Luke) am also under the impression that the meetings are not specifically about Bitcoin Core.  I agree that they tend to be dominated by Bitcoin Core concerns, but I think that's only natural because Bitcoin Core is doing so much highly-innovative-but-review-needing work and because so many Bitcoin Core developers are already hard core IRC users.

---

Going a bit off topic, I would like to find some way to work with the new Bitcoin Core website to cross-link content on each site that is relevant to readers of the other site.  I want our sites to be cooperative, not competitive, to the greatest degree possible.  I'm still thinking about reasonable ways to do this.

**Comment by harding** [comment]
Closing this; per a clarification in the BitcoinCore.org repository, the meeting are Core-focused.  In addition, not duplicating work for content already on that site would save me time.
