### ISSUE TITLE
"accounts" wallet functionality is deprecated

### ISSUE THREAD

**Issue by pstratem** [bitcoin-dot-org/bitcoin.org#1287]
https://bitcoin.org/en/developer-reference#sendfrom

(etc)

**Comment by laanwj** [comment]
To be clear: it would be nice to add a deprecation notice, like we did in the RPC help:
https://github.com/bitcoin/bitcoin/commit/7b782f5

**Comment by charlesfries** [comment]
Anyone have a recommendation for an alternative accounting system? Trying to avoid writing it myself. I'm heavily reliant on this functionality in my application, currently which is probably a bad idea

**Comment by tinspin** [comment]
So what is your official recourse to "off-chain" transactions now that you depreciate the only "working" solution to the most important problem with bitcoin. Implement it yourself? If accounts don't scale then neither does the wallet since it uses the same database? Who is responsible for this part of the application?

**Comment by mmgen** [comment]
[My project](https://github.com/mmgen/mmgen) relies on this functionality.  Are you planning to replace it with anything, say a "comment" field associated with each address in the wallet?

**Comment by MarcoFalke** [comment]
@mmgen Yes, please have a look at https://github.com/bitcoin/bitcoin/pull/7729

**Comment by mmgen** [comment]
@MarcoFalke Thanks a lot!  That's exactly what I was hoping for.

**Comment by Mirobit** [comment]
Labelled all related functions and fields as deprecated in #1429
