### ISSUE TITLE
I'm Stuck

### ISSUE THREAD

**Issue by michaelperales** [bitcoin-dot-org/bitcoin.org#1309]
Hi 
I opened a wallet. Bitcoin Core. I then requested a payment (see attached) then sent the information to a friend to send payment.
Here is my request Payment information**

URI: bitcoin:15nqxx9xvbqsqzui96C8Pd8v2XXEUeqtRp?amount=700.00000000&label=Heritage&message=Payment%20from%20Heritage
Address: 15nqxx9xvbqsqzui96C8Pd8v2XXEUeqtRp
Amount: 700.00000000 BTC
Label: Heritage
Message: Payment from Heritage

Now what do I do? They have sent it since yesterday.Here's what they wrote:

This is the address that we sent the funds to yesterday:
 
15nqxx9xvbqsqzui96C8Pd8v2XXEUeqtRp
 
This is the address it should have come from:
 
1HQBeT2GLBJ9D4mCyBVb5Ct1qDYj4J9udW
![bc](https://cloud.githubusercontent.com/assets/19830446/15980716/611506d6-2f22-11e6-9603-d6a99b6b5cd3.png)

Please help.

Thank you,
Michael Perales

**Comment by theymos** [comment]
This isn't the correct place for support. The [bitcointalk.org tech support forum](https://bitcointalk.org/index.php?board=4.0) or [/r/Bitcoin](https://www.reddit.com/r/Bitcoin) would be better.

But, in answer to your question: [1.213592234 BTC was sent to that address](https://blockexplorer.com/address/15nqxx9xvbqsqzui96C8Pd8v2XXEUeqtRp), but Bitcoin Core will typically not show received payments until it has completely synced. So you need to wait until the thing at the bottom of the Bitcoin Core window that says "x years/weeks/hours behind" gets to zero. On most computers, this will take a few days to complete. Lightweight wallets such as Electrum don't have this wait, but they work by trusting a third-party, which is why Bitcoin Core is still recommended for people who can tolerate the wait. (This is all mentioned on the bitcoin.org "choose your wallet" page.)

If you need the BTC urgently, it is *possible* to access them without waiting for Bitcoin Core to sync, but it's a bit complicated.

**Comment by michaelperales** [comment]
It says over 2 years!



________________________________

**Comment by theymos** [comment]
That's how far back the section of block chain you're currently processing is. It's not how long it's going to *take*.

**Comment by michaelperales** [comment]
Thank you for the quick reply.  Should I be able to receive within a couple of days? I send the request June 9th.


________________________________
