### ISSUE TITLE
Rethink the listing of Coinbase

### ISSUE THREAD

**Issue by nopara73** [bitcoin-dot-org/bitcoin.org#1336]
This discussion has araised multiple times in the past.  

https://github.com/bitcoin-dot-org/bitcoin.org/pull/1178 - First Coinbase was delisted before, because it was running Mike Hearn's XT in production. 
https://github.com/bitcoin-dot-org/bitcoin.org/pull/1180 - Shortly afterwards because of [public pressure](https://www.reddit.com/r/Bitcoin/comments/40i70i/bitcoinorg_violates_its_mission_statement_to/) the delisting was reversed. 
https://github.com/bitcoin-dot-org/bitcoin.org/issues/1254  - Later it was proposed again, because its [CEO defined CB as an exchange, emphasized it is NOT a wallet](https://medium.com/the-coinbase-blog/coinbase-is-not-a-wallet-b5b9293ca0e7#.eyh3zso12) and exchanges are not to be listed here. It is still an open issue.  

Based on the concerning way they handled the Ethereum hardfork I would like to propose to **rethink the listing of Coinbase** again. 
Details: @taoeffect : [Clarifying The "Free ETC" Coinbase Confusion](https://gist.github.com/taoeffect/c910ebb16d9f6d248e9f1f3c6e10b1b8) 
Summary: they were not prepared for replay attacks after the hard fork, so people started to hack Coinbase out of its ETC (original Ethereum chain, stands for Ethereum Classic) by withdrawing ETH. What made some poeple [question their solvency](https://bitflikz.com/blogs/news/critical-security-update-from-bitflikz-gdax-coinbase-may-be-insolvent), furthermore they do not allow their customers to withdraw their ETC.  

In case of a Bitcoin hard fork the "it will probably work out fine" attitude of Coinbase is concerning, especially for a closed source custodial wallet might be a recipe for disaster.  

An other issue is the exponentially [growing number of complains](https://www.reddit.com/r/Bitcoin/search?q=coinbase&sort=new&restrict_sr=on)  about Coinbase.  

In the light of recent events I would like to reopen the discussion on removing Coinbase from the "Choose your Wallet" page.

**Comment by g4p** [comment]
+1 - Evict Coinbase.

Bitcoin.org has a goal to serve the community, the community is not well served by Coinbase, remove them.

**Comment by keo** [comment]
👎 

Coinbase as a business chose to not support the minority chain. If you had ETH with Coinbase before the fork, you chose to support what they support, and they clearly communicated they'll support the majority chain with the most proof-of-work.

Coinbase still functions as an easy to use Bitcoin wallet for millions of people.

Bitcoin supporting ETC or has nothing to do with their Bitcoin business.

Interesting to see though small blocker idealists suddenly being interested in and caring for Ethereum.

**Comment by nopara73** [comment]
If you keep your pre-fork Ethereum on Coinbase exchange and it decides to go with ETC and not giving your ETH back would you be ok with that?

**Comment by keo** [comment]
They said they'll go with the majority chain. I was ok with that (whatever currency that means after the fork).

If you're not ok with that, you should have withdrawn.

Back to your question – if I wouldn't agree with their decision to go with the majority chain I'd have withdrawn.

If I didn't withdraw I was simply stupid to keep it there and not caring about it.

ie. if you care – you take control. If you don't, or agree with your coin's custodian – take responsibility for acting as such.

**Comment by Cobra-Bitcoin** [comment]
I support removing them.

Their leadership keeps making bad decisions and they always seem to be trying to undermine Bitcoin in some way (XT, Classic, Ethereum, etc). I don't know why any sane person would use their services.

It's not really the sort of company we should be pushing new users too, Coinbase is too irresponsible and keeps forgetting that they're essentially a bank and shouldn't be behaving like a careless startup keen to "move quick". I'm very glad more people are starting to realize the truth about Coinbase.

**Comment by taoeffect** [comment]
Strong support. 👍

Was reminded of this issue as Brian Armstrong [just tweeted some propaganda from Bill Gates](https://twitter.com/brian_armstrong/status/759456910596640768) wherein Bill Gates says that Bitcoin is problematic due to "terrorism or money laundering" and that the unbanked "aren't trying to be anonymous".

Brian has been constantly attacking or undermining Bitcoin since he has entered the ecosystem.

**Comment by keo** [comment]
@taoeffect don't forget that they brought in millions of users who made a nice price pump for your Bitcoin holdings.

**Comment by taoeffect** [comment]
> @taoeffect don't forget that they brought in millions of users who made a nice price pump for your Bitcoin holdings.

I don't forget that. That is the only reason they're even a thing.

But if you have a friend who happens to be a serial killer, do you introduce him to your friends as, "Oh by the way this is Bob, he makes really latkas!" And do you keep being friends with him just because he has a few redeeming qualities?

**Comment by taoeffect** [comment]
> But if you know a person who happens to be a serial killer, do you introduce him to your friends as, "Oh by the way this is Bob, he makes really great latkas!" And do you do business with him just because he has this redeeming quality?

This probably wasn't the greatest analogy, as the issue isn't even so much he's doing "bad things [to someone]", but that he's "doing bad things *to us*". So the "keep business separate" arguments don't apply here. There are ethical and business reasons to removing Coinbase from the website. It only makes sense to support those companies that support Bitcoin and aren't trying to either destroy or undermine it.

**Comment by StarenseN** [comment]
@keo You're making assumptions about Coinbase who brought 

> millions of users

How can you assess that ?

Secondly

> @taoeffect don't forget that they brought in millions of users who made a nice price pump for your Bitcoin holdings.

I don't think that Coinbase had even a minor role in price pump. Still, today, it's irrevelant to any price action.

**Comment by crwatkins** [comment]
@nopara73 thanks for starting this discussion.

I try to make recommendations based on our [wallet criteria](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/README.md#wallets) document, with the thought that we should try to follow it as closely as possible and if we don't agree with it, then we as a community should change it.  There are certainly a lot of good reasons to change it over time as we are living in a very quickly changing environment with new information and new insights available constantly.

@nopara73 [proposed discussion](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1336#issue-168454903) of issues in the areas of (my summary):
 * Handling of the Ethereum hardfork
 * General attitudes relating to the hardfork and potential consequences to Bitcoin
 * Consumer complaints

I believe the wallet criteria that best apply to these issues are:
 * No indication that users have been harmed considerably by any issue in relation to the wallet
 * No indication that security issues have been concealed, ignored, or not addressed correctly in order to prevent new or similar issues from happening in the future

I concede that the application of these criteria can certainly be subjective, so I believe we should at least try to be consistent.

At this point, one week into the Ethereum hardfork, I cannot say with certainty what the best handling of the situation is.  @taoeffect makes some good points, as does @barmstrong [here](https://medium.com/the-coinbase-blog/on-the-ethereum-hard-fork-780f1577e986#.rc3029y1t). I can't personally conclude that the criteria are not being met (particularly regarding Bitcoin), so I cannot recommend delisting based on the above issues at this time.

Custodial wallets are a particularly tricky topic to deal with and I don't believe that we actually have enough guidance in our criteria to deal with them (#1109), but in the meantime, I use what we have to guide my recommendations.

**Comment by GwaD** [comment]
Completely disagree.

I definitely don't like their vision and proactive KYC stance either, but the arguments presented here are completely irrelevant. The decisions Coinbase took regarding some random altcoin shouldn't have any influence whatsoever in our trust in their capacity to ensure a reliable bitcoin custodian service, which is the reason why they are listed on this website. 

Coinbase still is the primary access gate for many people in Bitcoin, and such delisting would severely undermine the bitcoin adoption and image among the general audience. To date, Coinbase has been one of the rare online bitcoin wallets that didn't experience any security breach. 

The vendetta against Coinbase must stop. Let's move on to more important matters.

**Comment by keo** [comment]
> There are ethical and business reasons for removing Coinbase from the website. It only makes sense to support those companies that support Bitcoin and aren't trying to either destroy or undermine Bitcoin.

@taoeffect so you're saying that Coinbase's and @barmstrong's business model is to undermine and/or destroy Bitcoin?

**Comment by keo** [comment]
I think everyone's doing their best here to support and grow Bitcoin, and we may have different views on that. This is a very subjective topic.

My opinion is that Adam Back (@adam3us), Greg Maxwell (@gmaxwell) and Michael Marquardt (@theymos) are undermining and destroying Bitcoin in different ways. 

We also run an exchange and 90% of our support costs comes from customers not understanding why Bitcoin transactions are slow to confirm. I'd like to see a more pragmatic way for Bitcoin to scale.

**My opinion is hardly relevant due to the subjectivity of the topic.

@taoeffect having an opinion that Coinbase and Brian Armstrong (@barmstrong) are consciously trying to destroy Bitcoin is also hardly relevant.**

Let's concentrate on facts everyone can handle easily without many emotions: they're providing a great custodial and exchange service for many people and they never had any (known) security breaches.

This looks more like a fanatical jihad to me than anything that's well thought, sane and consistent.

**Let's stop bashing people and companies and let's build something great instead that benefits everyone.**

**Comment by nopara73** [comment]
@keo Great suggestion, yes, let's not go into the flame war and stick with the facts.  
Coinbase did not handled properly the hard-fork of Ethereum as a result people lose money.  
While Ethereum's advantage is that it is a quick moving innovative cryptocurrency, Bitcoin's is its security.  
Coinbase is a security concern.

**Comment by Daunus** [comment]
ack

**Comment by luke-jr** [comment]
Coinbase (via Charlie Lee) claims they will refund all ETC to people who had deposited/acquired it on their exchange prior to them discontinuing ETC support. If that is true, I don't see a problem at that level.

However, Coinbase has publicly stated they do not wish to be a wallet provider, so IMO they should not be promoted as one. ACK removing on that basis.

**Comment by gmaxwell** [comment]
I was pretty bummed to log into my coinbase account for the first time in a long time, only to be greeted with a pop up encouraging me to buy Ethereum. (not to /sell/ ethereum, which they also support, mind you.).

In the past issues with wallet listings were resolved by setting clear, defensible standard for it and working through the listing on that basis. If there is a standard here that Coinbase isn't meeting, others likely aren't either, and I hope the site would hope to be consistent-- as that is the most useful for the community.

I'd urge people here to do an analysis according to published criteria, and if the result is unreasonable under them fix the criteria and apply it consistently. Doing so will elevate the site by increasing the quality and consistency of the listings.

I don't know the details with the coinbase not wanting to be a  wallet mentioned above, but if that is the case it might be prudent for one of the bitcoin.org administrators to simply ~ask~ coinbase if they even want to be listed as a wallet.

**Comment by jonasschnelli** [comment]
Maybe bitcoin.org should also consider adding appropriate warnings (potential issue we see when using coinbase) instead of removing it.

Warnings could result in a better user-awareness then just not listing.
The warnings could focus on "centralization"-, "security"- and "ethical/community"-aspects.

But I agree with @gmaxwell. Removing or adding warnings to the coinbase listing should be done together with posting a list of criteria.

**Comment by jonasschnelli** [comment]
For clarification, with "warnings" I meant something different like the current "info layer".
Maybe something like:
- disabling the coinbase icon (opacity 50%)
- adding a warning icon on the bottom right of the icon
- when someone click on it, show why coinbase is disabled (refer to the criteria)

**Comment by crwatkins** [comment]
@luke-jr said above:

> However, Coinbase has publicly stated they do not wish to be a wallet provider, ...

I don't believe that is exactly what was said in the oft-quoted [article](https://medium.com/the-coinbase-blog/coinbase-is-not-a-wallet-b5b9293ca0e7#.jm5o0r3gq
) by @barmstrong.  The emphasized (by the article) quote was: 

>  We set out to build a bitcoin wallet, but it turns out we were building a retail exchange.

Later in the article, @barmstrong also said:

>I also think a large number of people will continue to use Coinbase as a wallet (we have the #1 wallet on iOS and \#2 on Android for example) and that is perfectly ok, even if it isn’t our focus.

@luke-jr continued:

> so IMO they should not be promoted as one. ACK removing on that basis.

As I've [previously](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1254#issuecomment-192754710) commented on this topic, I don't believe that the nomenclature used (by anyone) affects the suitability for listing on bitcoin.org (nor does one feature or another being the focus of anyone's efforts).

@gmaxwell suggested:

> I don't know the details with the coinbase not wanting to be a wallet mentioned above, but if that is the case it might be prudent for one of the bitcoin.org administrators to simply ~ask~ coinbase if they even want to be listed as a wallet.

@barmstrong [recently thanked](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1180#issuecomment-170998436) @theymos for the listing, so I'm under the impression that Coinbase would prefer to be listed and will inform us if that situation changes.

**Comment by SartoNess** [comment]
I agree with jonasschnelli,about warnings but not only to coinbase,cobra why are you put again in the table the xt-classic.??is obvious your problem with coinbase and their decisions but you are not coinbase leader,you can take decisions about your company,your home and not for others

**Comment by nopara73** [comment]
I noticed this post [has been ganged by /r/btc](https://www.reddit.com/r/btc/comments/4vfck4/cobra_bitcoin_at_it_again_supports_removing/).  
I close this issue before the flame-war gets out of hand.

**Comment by petertodd** [comment]
@jonasschnelli ACK warnings idea.

**Comment by nopara73** [comment]
It is time to revisit this issue. While there are no hard written requirements for wallets here, but I think we can all agree wallets those [are actively freezing customer accounts](https://www.reddit.com/r/Bitcoin/comments/6hipuj/coinbase_disabled_the_freeross_account_after/) have no place here.

**Comment by Daunus** [comment]
@nopara73 All Bitcoin exchanges freeze customer accounts occasionally. Its part of the business.

**Comment by nopara73** [comment]
@Daunus Bitcoin exchanges are not listed on bitcoin.org

**Comment by harding** [comment]
Bitcoin.org now has an [exchanges page](https://bitcoin.org/en/exchanges), and I think it would be appropriate to move Coinbase there.

I believe this is tentatively planned and we're just working out the details for moving all the remaining full-custody "wallets" on the wallets page to somewhere else, as its rather a stretch to call someone else holding your money for you a *wallet* even in the Bitcoin metaphorical sense.  However, this entails a careful update to our policy so we don't force ourselves to delist partial-custody wallets such as GreenAddress, GreenBits, and BitGo.  

(There could be other concerns too; I don't remember the previous discussion well.)

**Comment by wbnns** [comment]
@harding This is correct, thanks for summarizing. 👍

**Comment by chriswheeler** [comment]
Does Coinbase Vault come under the 'partial-custody' definition?

**Comment by harding** [comment]
@chriswheeler Not the regular Coinbase Vault (which I think is just some extra time-delays and access controls on top of regular Coinbase) but the [multisig vault](https://www.coinbase.com/multisig) would likely satisfy the definition.

Looking at just their marketing page, it isn't clear to me what having the shared key "encrypted by your password" means.  If it's encrypted by a password that Coinbase otherwise has access to (e.g. your regular Coinbase password), I think it'd be difficult to equate that to the GA.it model, so we'd probably have to think about it some more.

**Comment by crwatkins** [comment]
@harding wrote 

> Bitcoin.org now has an exchanges page, and I think it would be appropriate to move Coinbase there.

Coinbase has already been moved to the exchanges page, but it just hasn't been removed yet from the wallets listing as I recommended [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1109#issuecomment-268252161).   We've done that with new "custodial/bank" listings, but we haven't yet cleaned up the old ones.

**Comment by 0-0-0-** [comment]
Coinbase needs to be removed from any promoted listing a moratorium on any advertising of their services.

**Comment by ChainQuery** [comment]
@harding Moving them to the exchange page seems like a good idea. 

CoinBase is a regulated business operating in the US and to expect them to do anything but operate in a manner that is in accordance with the laws of their jurisdiction is asinine. While I do not currently use their services they are many peoples first on ramp to BTC, and an important part of the community. Its sad to see bitcoin.org used a tool (again) to attack those with different views.

**Comment by jli225** [comment]
Coinbase has a goal to serve the community, the community is not well served by Bitcoin.org, remove them.

**Comment by Justin-Maxwell** [comment]
It should not matter whether coinbase see or promote or describe themselves as a wallet.  Bringing that up as a concern only reflects that the bitcoin.org criteria for what gets listed as a wallet must be insufficient.  Surely the only defensible policy is to see if they meet a defined set of criteria, and list, or not, accordingly.

I've no great love for coinbase, but any criteria that didn't end up with them being included on both the wallet and exchange lists would, to me, indicate a break with obvious and actual reality.
