### ISSUE TITLE
Bitcoin Knots should not be the first wallet displayed

### ISSUE THREAD

**Issue by Mirobit** [bitcoin-dot-org/bitcoin.org#1405]
I don't know why Bitcoin Knots is the first recommended wallet. 
[https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/_templates/choose-your-wallet.html](choose-your-wallet.html) has Core at first place.

For new users it is hard to see the difference between Core and Knots. Since the list is not hypothetically ordered users must think that Knots is the most recommended wallet. Which it is clearly not (less than 30 nodes).

**Comment by harding** [comment]
There are four groups of wallets (if I recall correctly: full validation, SPV, Blockchain.info-style web wallet, and Coinbase-style web wallet).  Each day, all the wallets within a particular grouping are randomly sorted so as not to give any wallet particular preference.

Since two full nodes are listed, that means that Bitcoin Core should be listed first half of the time and listed second the other half of the time.

Whether that's a good idea or not, I'm not sure.  One of the difficulties of maintaining this page in general is trying to balance neutrality with making the best recommendations.

**Comment by cloudnthings** [comment]
I don't see any of the grouping play a part but regardless, it is tricky trying to be (seen) as unbiased. The random order is simple and works fine for what it needs to do.

One question though, how was "less than 30 nodes" determined for Knots? Are there actual stats some where?

**Comment by achow101** [comment]
That "30 nodes" thing was probably determined by looking at
bitnodes.21.co which lists all of the reachable nodes that it can find.

**Comment by Mirobit** [comment]
Yeah I got the number from bitnodes.21.co.

Since I won't get consensus for removing Knots I will close this issue.
