### ISSUE TITLE
New event

### ISSUE THREAD

**Issue by allthingsgo** [bitcoin-dot-org/bitcoin.org#1420]
- date: 2016-12-06
      title: "Blockchain India Summit 6 December 2016 "
      venue: " Zero Field Labs/Hotel Shangri-La"
      address: "Connaught Place"
      city: "New Delhi "
      country: "India  "
      link: " http://europeindiaconclave.com/"

**Comment by wbnns** [comment]
@allthingsgo Hello, thank you for submitting this. Apologies that it didn't get merged in time - I see today is the 6th. If you have another event in the future, please do let us know. Also, if you could please inform us at least a couple of weeks in advance so that we have time to review it, we would greatly appreciate it.
