### ISSUE TITLE
Redesign the Exchanges page to make it like "Choose your Wallet"

### ISSUE THREAD

**Issue by i-rme** [bitcoin-dot-org/bitcoin.org#1494]
Currently the Exchanges page on Bitcoin.org (https://bitcoin.org/en/exchanges) is just a list of a few exchanges without any comment on them. There appears to be no scrutiny, no review nor comment on them, no requisite to be listed, there are no ways to compare them in any way to find what Exchange is the most trusted one.

Past events have showed us that most bitcoin users lose their coins not by choosing a bad wallet but by choosing the wrong Exchange. (MtGox, Bitfinex, Bitcurex, Bitquick, Shapeshift, Cryptsy, Bitstamp and many others (Full list https://magoo.github.io/Blockchain-Graveyard/)).

We must design the Exchanges page just like the "Choose your Wallet" one, we must categorize, scrutinize, review, flag and delist Exchanges that dont meet the minimum security requirements.

That way a novice user can make a wise decision and at the same time we can push for higher standards just like this website has already risen standards for web-wallets (See #663 regarding Blockchain.info).

I'll be happy to help with this as soon as this redesign starts.

**Comment by i-rme** [comment]
Furthermore, we could also inform users on Exchange fees, transfer/withdrawal fees and other cost associated with exchanging bitcoins. That way they would see the whole picture.

**Comment by kuzzmi** [comment]
Currently I'm finalizing the "Choose your wallet" refactor to individual pages (#1661) which should make these pages more accessible. So keeping this in mind, and if there is a need, I can work on this issue afterwards on the technical side, or to support anybody who will, if I don't have enough spare time.

Evaluation of security levels as well as deciding which exchange is "good" or "bad" will be hard for me to do, but I can think about structuring the data of the exchange websites, so the next person can enhance it with such information.

**Comment by wbnns** [comment]
If anyone is interested in helping move this forward, perhaps the next step would be to provide a specification, along with guidelines for how exchanges would be reviewed. Some ideas:

- Able to use website without issues, on both desktop/laptop and mobile/tablet/handheld devices
- Review of various policies on site (privacy, terms of use, etc.)
- Search engine and social media for user issues and other feedback
- Has order book with sufficient depth in order to reduce volatility beyond general market conditions for end users
- Comparison of exchange rates with average bitcoin price (should be relative, rather than significantly higher or lower)
- Is relative to the category for which it is being added. For example, if the exchange is in Argentina, it should offer trading pairs for bitcoin relative to the Argentine peso. The site should also be available in Spanish.
- Review of site security features such as multifactor authentication, new device verification, user-facing log of account-related actions for security audits, if available
- Review of wallet criteria on the exchange
- Review of API if available
- Volunteer(s) from locale to do test transactions and provide feedback
- Review of help documentation on site
- Review of customer service response time
- Review of account verification processes

There are of course other things that could be looked at. We could also randomly re-review exchanges on whatever criteria, randomly, within a given interval (monthly, quarterly).

**Comment by wbnns** [comment]
Closing; discussion to be continued in #3033.
