### ISSUE TITLE
Translation process

### ISSUE THREAD

**Issue by Mirobit** [bitcoin-dot-org/bitcoin.org#1508]
How are translations normally handled? Via Transifex or via Github? There needs to be a clear procedure otherwise there is chaos.

For example the [notesync](https://bitcoin.org/en/download) string:
- Bitcoin.org EN: over 100GB
- Bitcoin.org DE: über 65GB
- Transifex DE/EN: über/over 20GB

Shouldn't Transifex always contain the most current strings? Otherwise the maintainer doesn't know which version is correct if the string was edited on Github and Transifex.

**Comment by wbnns** [comment]
@Mirobit Hello, thanks for raising this issue. Yes, there is a good bit of work that needs to be done to keep everything in sync. Here are details on how it works:
https://github.com/bitcoin-dot-org/bitcoin.org#how-to-translate

More specifically, it's not as simple as just uploading new English strings to Transifex, because it will cause previous translation work to be lost (which was an enormous multi-year effort) and new translators would have to begin anew (not good). The current pending TODO is to use the Transifex CLI to scrupulously get everything in sync, and then have a weekly standard operating procedure to coordinate with the translators to make sure the different languages are continuing to remain in sync (or progressing toward full coverage if they aren't 100% complete) going forward, so the current situation of them getting out of date can be avoided.

***

An example of the current technical process is as follows - here's a string, `helptxt`, `https://github.com/bitcoin/bitcoin.org#how-to-participate` becomes `https://github.com/bitcoin-dot-org/bitcoin.org#how-to-participate`

We need to:

- Download all latest translations from Transifex using their client
- Use a sed command to update `helptxt` in all languages programmatically
- Diff the folder to ensure the command did the right thing
- Push to Transifex

This in turn will have updated 25+ translations (the existing ones we support, but also all incomplete translations that may have this string translated, even though they are not currently in use just yet - but will be, once complete).

The above process would need to be done for other strings as well (like the `notesync` string you mentioned). There are a significant number that need to be revised like this.

I hope this clarifies things. If you're interested in helping (or if anyone reading this is), it would be most appreciated. This is definitely a priority that's on the horizon to be tended to. 

Please let me know if you have any questions.

**Comment by wbnns** [comment]
@Mirobit Hey, just a heads up that I'm closing this and am going to split the topic of translation updates into several smaller issues (e.g. updates relating to specific languages), that people can contribute to resolving if they would like to get involved.
