### ISSUE TITLE
Bad wallet summaries

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#1515]
"Simplified validation" should be "negative" orange.

Bloom-using wallets shouldn't say they have any privacy.

**Comment by greenaddress** [comment]
Mostly agree however if you connect to your own Node via Onion/SSH tunnel/VPN then you do have your privacy.

**Comment by crwatkins** [comment]
Thanks for pointing this out.  I'll try to explain how I think the current scoring is supposed to work.

The validation scoring relates to trust and not privacy.  We currently give wallets that use random servers a better score (color) than those that use centralized servers.  I'm definitely not opposed to making improvements in this area, but I personally think that this is an important distinction we should continue to emphasize.

**Comment by evoskuil** [comment]
@greenaddress Only query privacy, you remain unprotected against new transaction taint. That requires using a distinct anonymized connection to a *public* node (vs. your own node) for each tx posted.

**Comment by greenaddress** [comment]
@evoskuil What if your own node is also only connecting via Tor? Then you only need a e2e encrypted/authenticated channel with your node

**Comment by evoskuil** [comment]
* When you post multiple txs over same same Tor channel they are correlated, since the other end can be the attacker and see them all arriving from one node first. It doesn't make a difference that you relay them though a node that you control.

* When you connect via Tor to your own node that connects only via Tor to peers, the node needs to drop each connection before sending your second tx (in order to prevent the first problem). The node also needs to guard against [unmasking](https://arxiv.org/abs/1410.6079), which is problematic.

* A connection to your own node via Tor/VPN/SSH protects only the communication. The tx still originates from a node that you visibly own.

**Comment by wbnns** [comment]
Hey all, thanks for the comments on this. Spoke with @crwatkins and am closing this for now as it seems there was a basically just a misunderstanding in regard to the validation score. If that assertion is incorrect, please let me know and we can reopen.
