### ISSUE TITLE
Where would be the best place to put Meetup on the Lawsuit against Bitlicense ?

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#1529]
Just wanted to know if it would be worth to add a section for the Regulations stories ?
http://www.article78againstNYDFS.com/press.html

It seems that there is more political stuff like this kind of document:
http://www.uniformlaws.org/Committee.aspx?title=Regulation%20of%20Virtual%20Currency%20Businesses%20Act

Should I start a new section ?

**Comment by wbnns** [comment]
@theochino Hello, if you're having a Meetup, you can [submit an event](https://github.com/bitcoin-dot-org/bitcoin.org/issues/new?title=New%20event&body=%20%20%20%20-%20date%3A%20YYYY-MM-DD%0A%20%20%20%20%20%20title%3A%20%22%22%0A%20%20%20%20%20%20venue%3A%20%22%22%0A%20%20%20%20%20%20address%3A%20%22%22%0A%20%20%20%20%20%20city%3A%20%22%22%0A%20%20%20%20%20%20country%3A%20%22%22%0A%20%20%20%20%20%20link%3A%20%22%22) so that it can be added to the website.

Regarding a section for regulations, this might be hard to keep up to date, as it could be quite extensive and fast-changing. For example, [BitLegal](http://bitlegal.io/) is one website that is solely dedicated to this.

**Comment by theochino** [comment]
I sent email to the BitLegal email but it was returned. Do you have any contacts ?
Yes, it's fast changing but we need to organize around that .... otherwise we will lose.

**Comment by wbnns** [comment]
I see, no, I don't believe I know anyone over there.
