### ISSUE TITLE
wallet address issue

### ISSUE THREAD

**Issue by flujodedinero** [bitcoin-dot-org/bitcoin.org#1562]
Source File: _posts/2016-12-31-updated-instructions-full-node.md

hello there, could you please help me to resolve this issue:

My wallet is not generating addresses enough, everytime it reaches 100BTC it starts repeating the last address.
How can I be sure my wallet is going to create unlimited and unique addresses?

Thanks for your answer

**Comment by wbnns** [comment]
Hello @flujodedinero , instead of opening an issue, please try seeking technical support in one of the following places:
- [Bitcoin Stack Exchange](http://bitcoin.stackexchange.com/)
- [BitcoinTalk Development & Technical Discussion](https://bitcointalk.org/index.php?board=6.0)

Apologies, we don't provide direct support in this context here on the repository.
