### ISSUE TITLE
i don't receive my bitcoin in my wallet

### ISSUE THREAD

**Issue by xM7MDx11** [bitcoin-dot-org/bitcoin.org#1612]
Hello i am use bit core wallet i don't receive my bitcoin from yesterday 

You can see the transaction information here: https://tradeblock.com/bitcoin/address/1SE9srHc59T7isjtSGiqFmHMFfz8HkcRj

**Comment by wbnns** [comment]
@xM7MDx11 Hello, sorry to hear you've experienced a problem. I'm going to close this issue since it doesn't pertain directly to Bitcoin.org, however, I'm happy to try to help you take a closer look into what happened and attempt to point you in the right direction. Please email me at will@bitcoin.org if you still need help.
