### ISSUE TITLE
Add ukrainian bitcoin exchange to exchanges list

### ISSUE THREAD

**Issue by pop4tune** [bitcoin-dot-org/bitcoin.org#1615]
Hi, 

as I can see there is no any Bitcoin exchanges from Ukraine in the exchanges list at https://bitcoin.org/en/exchanges

Can you please add Kuna.io in this list and mark it from Ukraine?

**Comment by sherika36** [comment]
https://bitcoin.org/en/exchanges/Kuna.iofromUkraine

**Comment by sherika36** [comment]
mojombo#1
mojombo/github-flavored-markdown#1https://bitcoin.org/en/exchanges/Kuna.iofromUkraine

**Comment by sherika36** [comment]
Ok no problem i think i did it. Did i? Or did i forget something

On May 30, 2017 6:30 AM, "pop4tune" <notifications@github.com> wrote:

Hi,

as I can see there is no any Bitcoin exchanges from Ukraine in the
exchanges list at https://bitcoin.org/en/exchanges

Can you please add Kuna.io in this list and mark it from Ukraine?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin-dot-org/bitcoin.org/issues/1615>, or mute the
thread

**Comment by pop4tune** [comment]
No, unfortunately I can't see it. 

No such page as Exchanges in Russian at all. 
In English it wasn't added - no section "Ukraine", no Kuna.io

**Comment by sherika36** [comment]
bitcoin:34vDbxqhk7z9JgNS8XAfUxWFF2h4BGBBVu?amount=1

**Comment by achow101** [comment]
... @sherika36 what are you trying to do? The page won't exist unless a pull request that adds it is created and merged. Whatever you are linking to is incorrect, and whatever you think you added does not exist unless a commit is made and a pull request for it created and merged.

**Comment by Mirobit** [comment]
Done (#1621)

@pop4tune The page is quite new and hasn't been translated so far.

**Comment by pop4tune** [comment]
I can translate it. 

See you joined same requests in one.
