### ISSUE TITLE
Voucher Section

### ISSUE THREAD

**Issue by nvk** [bitcoin-dot-org/bitcoin.org#1640]
Hello, I'd like to note that Opendime is not a "Voucher" like the other's listed in the category. With Opendime you actually own the Bitcoin, the private key is yours which is not the case for the others listed. Since the adoption of Opendime has grown substantially. I think a new Category under choose your wallet would be more appropriate. It could be called "Others" or "Single Use" where you could also list paper wallets. 

Thanks!

R.

**Comment by wbnns** [comment]
@nvk Hello, thanks for the feedback. We would need to wait until there are multiple products that match a certain criteria before considering the addition of a new category on the wallets page.

**Comment by nvk** [comment]
It could alternatively just be listed under Hardware wallets.

**Comment by harding** [comment]
I don't think one-time-use instruments such as OpenDime and so-called paper wallets belong on the wallets page.  A physical wallet has the ability to accept many deposits and many withdrawals, and that is also the case for all the software and hardware currently listed on the Choose Your Wallet page.  It would seem inappropriate to twist that wallet metaphor to cover paper keypairs, seed backups, Casascius coins, OpenDime, and other things that behave more like traditional bearer instruments than physical wallets.

In addition, I think that if we were to list such things on Bitcoin.org, we'd have to also address their unique safety and privacy issues (similar to how the bottom of the Choose Your Wallet page has a large warning that links to security-oriented pages).

I do think OpenDimes and Casascius Coins and other manufactured private key storage devices make nice gifts for small values of bitcoins, but they make me nervous when people use them for large values of bitcoin (either out of naivety or because price increases have turned a small value into a large value).  I think "vouchers" communicates that dichotomy with admirable conciseness, whereas to list them in almost any other way would require writing a boring technical warning.
