### ISSUE TITLE
Link to KYCPoll?

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#1676]
https://luke.dashjr.org/programs/kycpoll/

Thoughts?

**Comment by harding** [comment]
Seems interesting enough that it could be included on the [community page](https://bitcoin.org/en/community) if there are at least two more similar entries we could add in a new section.  For example,

- https://vote.bitcoin.com/ (note, Bitcoin.com)
- https://hodl.voting/ (note, currently on testnet, manages private keys in the browser by default, requires storing private keys outside of a wallet, and seems like a great way to lose money overall; still, the idea is cool)

We could also add it to a section that's not specifically about polling.

**Comment by wbnns** [comment]
Ok, cool. I'll put together a PR to add this.

Side note: I don't think we should be linking to Bitcoin.com from Bitcoin.org.

**Comment by Mirobit** [comment]
@wbnns Agree not to link to Bitcoin.com. Other than KYCPoll or HODL it is a commercial site. Also we shouldn't push their PR.

**Comment by wbnns** [comment]
Hey, just a quick update on this - I haven't submitted a PR to add this because if we add a new section to the Community page, it changes the symmetry of the design (the number of sections is no longer equal). To fix this, we would need to add another subsequent section as well (and I'm not sure what should go there).

@luke-jr I'm going to close this for now, but if you have any suggestions or have any thoughts about another page that might be good for it, just let me know and I'll reopen.
