### ISSUE TITLE
Privacy Policy + Popup is not translated

### ISSUE THREAD

**Issue by reddr** [bitcoin-dot-org/bitcoin.org#1735]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **13,500 bits / ~$110 USD**

Both the Privacy Policy and the popup ("We use cookies to ensure..") are only displayed in English no matter which language is selected. On the Privacy Policy page only the two words "Privacy Policy" are translated. See screenshots below:

![privacy_policy](https://user-images.githubusercontent.com/28353286/29025638-11365a90-7b78-11e7-9c3d-8e4f4e557b76.png)

![privacy_policy_popup](https://user-images.githubusercontent.com/28353286/29025640-13f20b12-7b78-11e7-9fcf-b6a9e888a7a4.png)

**Comment by holaymolay** [comment]
reddr, does this bounty apply to each language translated? I can have my wife translate zh_TW

**Comment by wbnns** [comment]
@holaymolay Hi there! For this one, no, however, some new bounties are in the works, just for translators, that will allow them to be compensated for doing translations.

**Comment by LeopardFMZ** [comment]
I'll be happy to translate it to AR. Since I cannot find related lines about privacy in AR.yml, am I to copy the lines from the EN.yml one to AR.yml and translate it? if so, does it matter which line I should copy it to in the AR.yml file?  Thanks!

**Comment by kuzzmi** [comment]
@wbnns as you added a bounty to this issue, could you please elaborate a bit, what should be done in scope of that issue? Is that adding a support for translations?

**Comment by Komodorpudel** [comment]
@kuzzmi I'm doing the German translation since 2013. The privacy policy and pop ups are translated since September. I told @wbnns  as soon as I was finished, that this can be updated. In general, the German version of the Website has not been updated for a year now (I believe).

I would be glad to put the current version into the repository myself and collect the bounty. However, I’m new at GitHub and a total noob in this regard. Asked @wbnns  if he could assist me, but it seems like my e-mail went missing. Asked @buren  if he could do it for me. He should be onto it.

In general, I believe that many translations of bitcoin.org are much older than the current versions at transifex.

**Comment by wbnns** [comment]
Opened #2707 to correct this. There was a conditional in the footer link that was preventing the translated page from displaying properly.
