### ISSUE TITLE
Remove copay from the "Choose your Wallet" page

### ISSUE THREAD

**Issue by friendsofbitcoin** [bitcoin-dot-org/bitcoin.org#1751]
https://archive.fo/U8v26#selection-215.25-215.100

Bitpay recently began to deceptively promote a contentious hard fork proposal and encouraging all bitcore nodes to upgrade to a consensus splitting change without replay protection which would endanger many users running copay or bitpay wallets. 

Lack of clarity on the risks this poses to users and dishonest representation make this wallet unsuitable for the time being for recommendation.

**Comment by shesek** [comment]
ACK. BitPay's plans to migrate away from the Bitcoin protocol without with community consensus makes them an unsafe wallet that should not be recommended.

**Comment by theymos** [comment]
Agreed.

**Comment by nopara73** [comment]
There should be a set of guidelines as to which wallets can be listed. Unfortunately as long as open sourcing and not stealing and freezing customers' funds are still not requirements of bitcoin.org (see issue https://github.com/bitcoin-dot-org/bitcoin.org/issues/1336 )  CoPay's removal due to misguiding customers would not be consistent.

**Comment by friendsofbitcoin** [comment]
As far as I am aware the copay app in play store and apple app store is controlled 100% by bitpay's bitcore nodes, thus all copay wallets will indeed have their bitcoin funds frozen and will indeed be at risk of stolen funds without replay protection?

**Comment by paOol** [comment]
Core should add replay protection if worried about users funds as the result of the November hardfork.

**Comment by friendsofbitcoin** [comment]
@paOol This doesn't address the issue with slow historical node upgrades from users. Many users are going to be harmed by a hardfork spinoff lacking replay protection regardless if core adds replay protection or not.

**Comment by mariodian** [comment]
@friendsofbitcoin you can point Copay to your own server though.

**Comment by Mirobit** [comment]
Agreed. By supporting a hard fork without replay protection, users can lose their coins on the main/core chain. 

You can set a custom backend server but i think very few users know about this. 

But we need to adapt the requierements for wallets first.

**Comment by laudaa** [comment]
ACK.

**Comment by friendsofbitcoin** [comment]
@mariodian  while true the "Choose your wallet" page is primarily used to educate new users and 99.9% of them won't know how to setup a custom bitcore server or make those changes. We need to focus on risk mitigation and reducing loss of funds for new users.

**Comment by harding** [comment]
Maybe I'm misreading the page, but I don't think it says what's being claimed in this thread.  Specifically, it says:

> Bitcore-node v3 runs uses a modified version of Bitcoin Core 0.12.1

The rest of the instructions are about running a border node, specifically the HF'ing btc1.

If you use Bitcoin Core 0.12.1 with a btc1 border node, you will not hard fork because Bitcoin Core 0.12.1 will not hard fork.  Instead, the btc1 border node will accept the segwit2x mandatory >1MB hard fork block and relay it to the Bitcoin Core 0.12.1 node---but, critically, the Bitcoin Core 0.12.1 node will reject it as having an invalid block size.

At that point, Copay and other Insight-based won't show any further confirmations for transactions made after the HF block.  That's not good and we should certainly request that the Copay wallet authors address that concern, but (if I'm understanding this correctly) I don't think this requires immediately delisting under Bitcoin.org's hard fork policy.

**Comment by theymos** [comment]
PR:  #1752 

@harding It seems clear to me that they're using the SegWit stuff as a bait-and-switch to get people to feel that they must urgently run btc1.

**Comment by friendsofbitcoin** [comment]
@harding Good observation, except the last paragraph explains that in several weeks users will no longer need to run boundary nodes and the concern here is these lite clients push self upgrades in smart phones

**Comment by nvk** [comment]
:+1: alts have no place here

**Comment by lichtamberg** [comment]
**Full ACK**

**Comment by d1gitalflow** [comment]
ACK

See here: https://github.com/bitpay/bitcore-lib/pull/50

They seem to have no intention of adding that commit that is mostly a year and half long coding to support segwit.

**Comment by olalonde** [comment]
Segwit2x is not contentious, it is supported by most of the hash rate.

**Comment by chrisrico** [comment]
@friendsofbitcoin Copay is not "100% controlled" by Bitpay's Bitcore nodes. You can change to point at your own node, theirs are merely the default.

**Comment by luke-jr** [comment]
If someone wants to fork Copay, and adjust it to always stick to Bitcoin, that fork can be added. Copay itself seems to likely default to an altcoin, so it shouldn't be listed.

**Comment by runn1ng** [comment]
Currently, you *cannot* run bitcore/insight/copay/... with segwit2x node.

Not sure in what stadium is the bcoin implementation. bcoin is used there as the full node. I do not know which rules do bcoin support, but given their tone, I would guess they will use 2x rules.

But yeah, they are indicating they will make users switch, so maybe removal is justified in the end

**Comment by olalonde** [comment]
The original chain will slow to a crawl and become vulnerable to 51% attacks soon after the hard fork though. I think it'd reasonable for Bitcoin.org to recommend the most secure chain and wallets that support it.

**Comment by friendsofbitcoin** [comment]
@olalonde Over 99% of full nodes don't run btc1 . Even if we were so reckless to support segwit2x this would not protect many users from the damage caused by a rushed HF due to the slow upgrade path users take and lack of ability to communicate to everyone effectively. Thus we must cautiously avoid actions which place them at risk from loss of funds.

**Comment by shesek** [comment]
> Right now, they are still technically on bitcoin chain, no matter what they do or don't recommend. I am not sure about your rules, but currently, they are using bitcoin.

I think that expressing the intent to diverge away from the bitcoin chain to a new protocol that didn't gain community consensus is enough of a reason for removal, as a preemptive step against the future losses this would cause to the wallet's users.

**Comment by runn1ng** [comment]
@shesek if you want to run bitcore node with 0.14.2, start here

https://github.com/satoshilabs/bitcore

I am not sure how bitcore wallet service (necessary for copay) works 100%.

Note that you will need at least 300GB of space for bitcore alone, and probably should be an SSD, and should be a stable webserver.

**Comment by jgarzik** [comment]
NAK.

What happens if you continue to remove wallets that follow the blockchain w/ most hashpower?  Users are left with tiny list of holdouts that point to an insecure, slow chain.

**Comment by luke-jr** [comment]
@olalonde Why should Bitcoin.org recommend an altcoin just because SHA2 miners defect to it? That's absurd.

**Comment by shesek** [comment]
@jgarzik The hash power majority does not dictate bitcoin's rules. They follow it.

**Comment by TheButterZone** [comment]
ACK

**Comment by olalonde** [comment]
@luke-jr because Bitcoin's security model is based on the assumption that no single entity controls 50+% of the hash rate. This assumption goes out of the window after the Segwit2x hard fork. There will probably be more than one entity capable of attacking the old chain due to its low difficulty. If you don't want to follow the hash rate, you are left with changing the PoW algorithm.

**Comment by petertodd** [comment]
ACK

What BitPay did is a remarkably deceptive and dishonest thing to do. We should not advertise wallets from dishonest companies, so BitPay is out until they somehow restore that trust.

**Comment by JavierGonzalez** [comment]
@luke-jr Bitcoin is based on proof of work, for a security reason.

If you want a currency based on "developers who like takeovers" please create an altcoin for you and your friends.
Maybe you're right and a lot of people trust that.

Please try that without fucking Bitcoin.

**Comment by JavierGonzalez** [comment]
> The miners do not dictate bitcoin's rules. Bitcoin would be completely useless if they did.

@shesek I think you're totally wrong.
This confusion is the root of the whole conflict.

The GitHub hierarchy is like the IRC.
It is a vertical and rigid hierarchy.
It is the pure essence of authoritarianism.

A currency based on this will never be worth anything.
It would be completely useless. No one would trust this.

Bitcoin is based on PoW.
Because mining is expensive. And everything else (nodes, developers) is cheap.
We are cheap.
It is a harsh reality, but it is the truth.
And the shortage of bitcoin is based on this.

Bitcoin is in the hands of the miners totally.
And the developers must propose solutions that the miners want to accept.

**Comment by shesek** [comment]
Bitcoin is based on PoW for the purpose of ordering transactions into blocks, not for determining protocol rules. See [Bitcoin is not ruled by miners](https://en.bitcoin.it/wiki/Bitcoin_is_not_ruled_by_miners).

**Comment by JavierGonzalez** [comment]
@shesek That was true until some have broken the monopoly of Bitcoin Core by developing multiple client programs.
Because as I said, developing clients and deploying nodes is cheap, very cheap.
IP costs 5 $/month, node costs 20 $/month.

Miners will deploy nodes as needed when needed.
They have money and we must assume that they know how to do it.

As you know, nodes can not cast a negative vote.
And you can never force a hostile node to accept it.

This brings us to reality.
The miners rules entirely in a PoW-based crypto.

PD: And changing the algorithm only changes some miners for others, and eventually we will return to the same conflict (the attempt to steal future commissions from ASIC / GPU miners). Hehehe

What the fuck is playing here?

**Comment by vedran6** [comment]
ACK

While a network split is a bad thing in and of itself, at least more sophisticated users have the ability to choose what chain to follow. What Bitpay did is dangerous because:

1. Copay users won't know what chain they're on.
2. Copay users might inadvertently send their main chain bitcoins to a black hole and permanently lose them due to no replay protection. At least BCH had replay protection implemented using a  custom sighash flag.
3. It is dishonest and fraudulent to force consensus on unwitting users.

**Comment by windsok** [comment]
ACK

**Comment by omarshibli** [comment]
Hey @shesek 

This is a great idea, How may I help?
I have extensive experience in cloud infrastructure and Copay implementation specifically.

Please send more info at omar@commerceblock.com

Good luck and keep up the good work.

**Comment by CosmicHemorroid** [comment]
ACK

**Comment by jameshilliard** [comment]
@jgarzik 
> What happens if you continue to remove wallets that follow the blockchain w/ most hashpower? 

Copay does not appear to use the SPV security model where the wallet follows the most hashpower, it uses the centralized validator model where a centralized authority is effectively trusted blindly for confirmations, [this](https://github.com/bitpay/copay/blob/e2cd5650edc3554a2a9bc4ef9a2fcaa917d4d628/src/js/services/configService.js#L17)(`https://bws.bitpay.com/bws/api`) appears to be the server copay uses.

**Comment by SquirrelCoder** [comment]
Then which wallet do you recommend?

**Comment by is55555** [comment]
ACK

**Comment by runn1ng** [comment]
This debate is stupid

There is no reason why should bitcoin core website show a wallet, that does not support bitcoin core consensus rules and has its own consensus rules.

Unless we want to go into philosophical discussion of "what is bitcoin?" and "is bitcoin ABC bitcoin?" and "is bitcoin 2x / Unlimited / Classic / ??? bitcon?". Which is beyond the scope of this issue.

The only reason against removing copay is that *right now* it uses backend with bitcoin core consensus rules, but that will probably change. So... yeah remove it

**Comment by JavierGonzalez** [comment]
This space is censored.

**Comment by nvk** [comment]
I think there are two separate issues. Do I wish bitcoin.org was little bit easier to add things too. Yes. But, 

Copay/BitPay wont be doing bitcoin anymore, they have no place here.

**Comment by theymos** [comment]
Resolved by #1752.
