### ISSUE TITLE
Texas Bitcoin Conference

### ISSUE THREAD

**Issue by Kalercm** [bitcoin-dot-org/bitcoin.org#1759]
- date: 2017-10-28
      title: Texas Bitcoin Conference III
      venue: Canyon View Event Center
      address: 4800 Spicewood Springs Rd
      city: Austin, Texas
      country: United States
      link: http://texasbitcoinconference.com/conferences

**Comment by luke-jr** [comment]
@wbnns Texas BC Conf is promoting Segwit2x as Bitcoin, so IMO should not be included.

**Comment by luke-jr** [comment]
> The Texas Bitcoin Conference III is on a fast sprint!  This will be a hugely important event as Bitcoin prepares for the 2x of SegWit2x!  We are going to be talking about Bitcoin, Bitcoin Cash, Ethereum, Litecoin, Dash, Iota, and more.  (Let's not forget Austin's own Factom, Stash, and Decred). We will discuss the Value, the Funds, the Regulations, the Companies, the Projects, and the Use Cases of Distributed Digital Currencies and Blockchains.  In other words, we are going to focus on what our growing community needs and wants desperately to understand!

**Comment by wbnns** [comment]
@luke-jr Heya! To me that excerpt looks like they are just talking about it (not necessarily blatantly promoting). I think that 2X is going to come up as a topic of conversation in many gatherings in the short term due to the controversy and risks associated with it. If others think this shouldn't be included as an event, however, it's no problem to remove.

**Comment by crwatkins** [comment]
@luke-jr  I haven't looked at any program materials beyond what you posted above, but to me that just sounds like there will be discussions and perhaps sessions on timely Bitcoin topics.
