### ISSUE TITLE
Breadwallet seems to be planning to fraudulently move its users from Bitcoin to the 2X altcoin

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#1761]
https://www.reddit.com/r/Bitcoin/comments/6vew8h/psa_breadwallet_users_at_risk_of_losing_funds/

**Comment by Mirobit** [comment]
This is going to be an empty "chose your wallet" page.

**Comment by theymos** [comment]
In previous discussions, the consensus was that since headers-only wallets cannot easily detect these things, they should not generally be considered to be altcoin wallets as long as they are *currently* Bitcoin wallets. There's a reasonable case to be made that headers-only wallets are inherently insecure and should maybe be removed from bitcoin.org for that reason, but that's a different issue.

Though if someone created a fork of Breadwallet which fixed this issue, it seems to me that it would be strictly superior to list that fork instead.

**Comment by luke-jr** [comment]
It would be trivial for light wallets to download any possible block 494784 in full, and check the size of it.

**Comment by crwatkins** [comment]
I agree with @luke-jr that it would be trivial for wallets to check.  However, there are currently a lot of things that SPV wallets do not check, nor do we have criteria for them to check.  As I've been fond of saying in the past, I believe that if we want to have new criteria, then we should discuss them, add them, and then apply them consistently to all the wallets.

As @theymos alludes, I believe that breadwallet is currently acting as a Bitcoin wallet, just as many other wallets that are listed do (as @mirobit alluded).  The breadwallet team is being proactive in describing the current behavior of their wallet as well being open to discussing future behavior.

I don't believe anyone has proposed any specific action in this thread yet, so I'll leave it at that for me too.
