### ISSUE TITLE
I wish to participate on fraud control bitcoin scams 

### ISSUE THREAD

**Issue by desiecall** [bitcoin-dot-org/bitcoin.org#1779]
Dear all,
I'm from Australia, I wish to participate in developing new protocol which would need to give security to buyer and seller by BTC sale. 

we should need to develop something otherwise middle income holders will loose their entire income, because of fraud happening using BTC.

there are more than 15 websites scam the people and grab BTC

and I'm a lifemember from Bitcoin Australia.

Regards,
Hari Krishna
you cn reach me at ecommtradelinks@gmail.com

**Comment by Gonefishing76** [comment]
Coinbase locked me out of my account because they thought it was that. But then they let $176 transaction. Even though They thought my account was hacked. There should be some recourse and getting a pans back that were not supposed to be sent in the first place

**Comment by Gonefishing76** [comment]
* coinbase locked me out of my account because they thought it was hacked

sorry using talk to text and I didn't look at it before I submitted comment

**Comment by wbnns** [comment]
@desiecall Interesting - I would recommend trying to connect with others on a forum, [like BitcoinTalk's Project Development Board](https://bitcointalk.org/index.php?board=12.0), to see if anyone might want to collaborate with you.

@Gonefishing76 Sorry to hear that happened to you. Have you tried connecting with them on [r/Coinbase](https://www.reddit.com/r/CoinBase/) or writing to their Support team (support@coinbase.com)? We don't have much recourse to assist you as we aren't affiliated with them. In the future, you may want to consider keeping your funds in a wallet where you have 100% control over the private keys.

**Comment by Gonefishing76** [comment]
Dear all,

I have been in contact with Coinbase the entire time. Because I put the money in on my debit card so it went instantly in there and then I got locked out of my account because they thought it might have been hacked!!! And then I had told them well don't approve any orders that have been made or payments sent or anything until I am allowed back in so I can confirm what is not correct and what is not. That was Friday night the 26th of August. So I emailed numerous times I finally got Jordan G to respond and he said oh yes a payment went through it's right here in the block cypher or whatever it's called or block chain.  But it still in unspent so they haven't seen it. So instead of putting a hold on that or contacted Blockchain or something since they locked me out of my account because of hacking they DID NOTHING!!!! and I couldn't do anything for over 2 today's. It was gone by the time I was allowed back, in I couldn't put it in my wallet on Friday night, I was already locked out because I had a new iPhone 7 a new device. The whole thing is just really sticks. I did a lot of research though and I know that they went to a website and he's hidden himself but there is a bank and all kinds of information listed about the bank. So my last trick is to get an investigation started and give them all the information I have it and all the banking information.  And like I told Coinbase there's should be some type of recourse for that when you're locked out of your account for suspicion of hacking and then a payment goes through that's not authorized and now you're not responsible and it's so sorry too bad so sad, when I get you're taking a risk but when you can't even access your account because Coinbase has locked out of it that is something totally different. And then $180 basically is gone. SMDH. 

 Well thanks for responding I appreciate the feedback, but they should whoever's account that it went to they need to suspend that account and that Social Security number and all the stuff you have to do to sign up, they can't sign up anymore. But I'm sure they did/do nothing soooooo. 

Again, thank you for responding I really appreciate the feedback. Sincerely. Gonefishing76 👍😊🙏
