### ISSUE TITLE
Explicit statement that the impersonation twitter/etc accounts are fake

### ISSUE THREAD

**Issue by midnightmagic** [bitcoin-dot-org/bitcoin.org#1842]
Please post an explicit statement that the impersonation twitter accounts and others—by name—are fake so when we complain about Twitter's crappy, poorly-implemented impersonation policy, we have something in specific to point to.

**Comment by harding** [comment]
@midnightmagic I'm not aware of any Twitter impersonation accounts for Bitcoin.org, only for the Bitcoin Core project, so I think this issue should probably be reopened on the https://github.com/bitcoin-core/bitcoincore.org repository.  That said, I think it's a good idea and I'll throw together a quick page for that site.

(Note though that I have reported one of the fraud accounts to Twitter and even provided them with the @bitcoincore.org email address they demand in order to investigate, and haven't seen any action.)

**Comment by midnightmagic** [comment]
Thanks. I didn't want to give the scum any more eyeballs. Maybe I'll ping you on IRC.

**Comment by harding** [comment]
Note: I think this issue can be closed; BitcoinCore.org merged the page mentioning Twitter impersonation and had their official Twitter account verified, and (as I mentioned above) I'm not aware of any impersonation of Bitcoin.org.

**Comment by wbnns** [comment]
@harding Ok, thanks Dave.
