### ISSUE TITLE
Reconsider "Bitcoin.org plans to support Bitcoin Knots"

### ISSUE THREAD

**Issue by nopara73** [bitcoin-dot-org/bitcoin.org#1938]
I've just read today's announcement of Bitcoin.org about [Knots](https://bitcoin.org/en/posts/bitcoin-knots).

> the software presented on the download page will be Knots and not Core

While @luke-jr is a great developer and Bitcoin Knots is a great client, it makes zero sense to drop Bitcoin Core in favor of Knots in the name of "network resiliency".  

There are many non-consensus breaking, under-tested, small group of developers maintained full node implementations out there, and favoring one particular one may not be a good idea.

In my opinion Bitcoin.org should favor the most stable, most tested full node implementation (Bitcoin Core), as it's been the case so far.

**Comment by Mirobit** [comment]
Totally agree. Btc1 has shown what happens if software is not well tested and maintained by a single person. Also Luke-Jr has a tendency to implement changes (Anti Spam Filter, Full RBF) that have no consensus and could hurt businesses if not properly communicated.

I find it harder and harder to tolerate @Cobra-Bitcoin autocratic leadership. Bitcoin.org has become more and more a vessel for his personal agenda. I don't consider this a community based site any more.

I am out.

**Comment by mandelmonkey** [comment]
if its in the name of  "network resiliency" why not list core, knots, bcoin and btcd?

**Comment by Sjors** [comment]
I'm not familiar with Bitcoin Knots and I'm sure it's great software. I think it's a good thing to not list Bitcoin Core as a default choice, to make it more clear that this site does not represent Bitcoin Core.

Slightly off-topic, but it would be good to add a better disclaimer to that effect, like bitcoin.com's disclosure:
<img width="315" alt="schermafbeelding 2017-11-23 om 20 07 18" src="https://user-images.githubusercontent.com/10217/33185278-3066db12-d08a-11e7-9471-0b8e926aadb7.png">

**Comment by Sjors** [comment]
I also can't find any peer review, not even a pull request, for this latest blog post. The commit wasn't signed either: https://github.com/bitcoin-dot-org/bitcoin.org/commit/c4bd860aa2799b61f4b35fdf7b54326dc0fc3116

This is unusual for bitcoin.org; perhaps an account was compromised?

**Comment by achow101** [comment]
@wbnns Just reverted it: https://github.com/bitcoin-dot-org/bitcoin.org/commit/71e9b7c00fa9de38fada66196b151dbec56d51a0

**Comment by Sjors** [comment]
@wbnns thanks for reverting that

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

I've reverted `c4bd860` with `71e9b7c` based on the following criteria:
+ This is a major change to the site, and there was no issue-related or PR discussion beforehand.
+ @theymos informed me he did not consent to the change.
+ There seems to be no consensus or agreement privately amongst contributors, or publicly with the community, whatsoever, warranting this change.

**Comment by jameshilliard** [comment]
@Cobra-Bitcoin While it's good to have diversity Knots shouldn't be recommended as a default. It's basically core with pull requests still undergoing code review/testing included along with a few other patches. It should be made clear that the average user should not use it unless they need a specific feature only it has.

**Comment by Sjors** [comment]
It should probably be more difficult to publish changes in this repo to the real site. This particular change is merely controversial, but if any of the maintainers Github accounts is ever compromised, that could be used to put malware on the site.

A good first step would be for the deploy script to check the GPG signatures against a whitelist. But I suspect there's a limit to how much protection Github pages can offer.

**Comment by victorperin** [comment]
Hey everyone,
I just want to point that this was a really weird commit. I think his account was compromised or something like it.

Also, he never pushed anything to master:
![image](https://user-images.githubusercontent.com/5847145/33191664-b41729ae-d0a2-11e7-8a6c-50c5126e947b.png)

So, I support @Sjors idea of making safer deploys.

**Comment by Cobra-Bitcoin** [comment]
We currently recommend Bitcoin Knots anyway. The only thing different in this potential new scenario is that downloading Core will be shifted to happen externally by pointing users to bitcoincore.org, while users will be able to download Knots directly from us. When you really think about it, it's not that big of a deal. Everyone seems to critiquing Knots as if we aren't already recommending it to new users. This scaling drama has made everyone in the community extremely sensitive to anything that can be _seen_ to undermine Bitcoin Core. We have to stop being so paranoid about perception.

I assumed most people wouldn't really care this much about which full node client happens to get its binaries distributed on bitcoin.org. We're not the official site for Bitcoin right? Considering the merge was only a blog post about **plans** to start supporting Knots, I didn't think it needed extensive discussion. Nothing was actually changed. I also have a difficult relationship with @wbnns sometimes, so I preferred to just get it merged and done, but it turns out he reverted it, something I didn't expect.

Rest assured that any change to the downloads page would have **_always_** gone through the pull request process.

**Comment by nopara73** [comment]
@Cobra-Bitcoin You have to admit, what you did was pretty sneaky (get it?:)

**Comment by ekerstein** [comment]
@Cobra-Bitcoin Why not just redirect users to external sites in both cases? Educate them about what Core is, then link to their site. Educate them on how Knots is slightly different, and contain a link for that too. Explaining the different implementations would be very useful I think.
