### ISSUE TITLE
Donations address should be multisig

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#1941]
I propose all the money collected in the bitcoin.org donations addresses be put in a 3 of 5 multisig address. Currently all the money is held by @wbnns and there's no way for us to recover should something happen to him.

Maybe the following people could hold the money: @theymos @luke-jr @wbnns @TheBlueMatt @crwatkins. Or anyone else?

**Comment by luke-jr** [comment]
Considering the current situation, I think it would be better that I not be a signer on this. At the same time, care should be taken that signers know and accept upfront the specific conditions under which they should sign over funds. (And if those conditions are simply "the owners say so", then the owners should also be the signers.)

**Comment by wbnns** [comment]
For the public record, this is Cobra posturing and playing a game of thrones to try to exert his influence over funds, because right now he doesn't have it, unlike everything else related to the site. He already asked me a couple of months ago to transfer everything to him so he could sell it all for USD because he thought bitcoin was "too volatile" - no mention of shared access with anyone.

He only recently raised this issue of shared control in private, as a straw man tactic to deflect attention away from concerns several people had raised, myself included, about at least one of his personal accounts getting hacked (he used a weak password and someone guessed it). This followed a disappearance of several weeks, with no reply to maintenance-related emails concerning Bitcoin.org, two of which, were security-related.

Now he's raising this issue in public after I reverted his commit yesterday - an announcement to the world, that Core will be dropped from Bitcoin.org and Knots will be the default going forward (many people noticed this announcement and objected to the change; a long-time contributor, Mirobit, also dropped from the project). This announcement was a unilateral decision made with zero input from contributors or the community, pushed directly to `master` as part of an intentional effort to circumvent any form of peer review and/or professional discussion.

In addition to the above three events (requesting to withdraw/remove all funds, getting hacked, and dictatorially announcing a contentious switch to Knots) there are a number of other questionable events that have happened in recent months:

+ Cobra moved Bitcoin.org to a DigitalOcean instance, terminating a robust DDOS-protected setting and eliminating a key-signed deployment environment - despite having access to both funding or donated hosting to avoid this (Saivann immediately dropped from the project following this)
+ Cobra suggested it was OK for NY Agreement people to receive death threats and that there should be no mercy for them, and that assassination markets have been put into place historically for a reason (he later deleted these comments from #1836; John Newberry immediately dropped from the project)
+ Soliciting a web development company in the Ethereum community, yesterday, to redesign and recode Bitcoin.org (essentially putting it into private control), create a new download page for Knots (alongside his announcement yesterday), without any formal due diligence or RFP initiative, much less else open feedback or public discussion amongst talented people who reside in our own community.

All of this combined, I'm concerned that he's basically become a corrupted, Denethor-like steward of Bitcoin.org at this point, bent on changing Bitcoin's PoW, with the first step in the execution of that strategy being a switch to Knots.

**Comment by windsok** [comment]
Has the donation address changed recently on bitcoin.org?

It used to show 1GwV7fPX97hmavc6iNrUZUogmjpLPrPFoE, which currently has a balance of 8.76626498 BTC

It is now showing 3FkenCiXpSLqD8L79intRNXUgjRoH9sjXa, which currently has a balance of 0.19192155 BTC, and received it's first transaction in the last few days.

**Comment by wbnns** [comment]
@windsok

Hello, yes, this was to update to a SegWit-enabled address. Also, for anyone who is interested, there has always been a publicly accessible spreadsheet with a [record of receipts and expenditures](https://docs.google.com/spreadsheets/d/1QxDq_9mOvammyfpRyQ8CvUUDsnlyLhx_kTYOBDERM30/edit?usp=sharing) maintained for additional transparency that anyone can review.

**Comment by Cobra-Bitcoin** [comment]
@wbnns This issue was to discuss moving the money to a multisig, something which almost anyone can understand is a good idea. I don't understand why you want to derail this discussion by launching a personal attack on me, but since you seem determined to attempt to smear me in public instead of communicating through IRC / Slack or email to resolve differences, I feel I have to respond:

> He already asked me a couple of months ago to transfer everything to him so he could sell it all for USD because he thought bitcoin was "too volatile" - no mention of shared access with anyone.

This was in anticipation of the 2X fork, I wanted to preserve what value we had to be able to pay bounties and do design work, and then buy back into Bitcoin after the hard fork and things calmed down. This was also a subtle way for me to let you save face and test your trust, and to later move back the BTC into a multisig address, a test which you failed dramatically by demanding I give you root access to the server before you move the money to a multisig address. These demands happened on IRC, and a few people where present in the chat at the time; if anybody that was in the chatroom has a log of these conversations, please do share (the entire thing if you can, not just parts out of context).

> This followed a disappearance of several weeks, with no reply to maintenance-related emails concerning Bitcoin.org, two of which, were security-related.

I resolved those issues after a delay. Sometimes people get busy. That's life.

>  This announcement was a unilateral decision made with zero input from contributors or the community, pushed directly to master as part of an intentional effort to circumvent any form of peer review and/or professional discussion.

A unilateral decision... like that time I woke up one day and saw your own personal address splashed all across the site? Where was the pull request about putting an address controlled by only **_one person_** on to the site? Show me the pull request if you can. You even changed the address again recently, with no discussion. It seems you feel like bitcoin.org is your vehicle to just collect money to your addresses, without input from the community about how this money should be managed and by whom.

> ...after I reverted his commit yesterday

Notice how when you made commits I didn't like, I raised my concerns in private, and didn't publicly embarrass you by reverting them?

> Cobra moved Bitcoin.org to a DigitalOcean instance, terminating a robust DDOS-protected setting and eliminating a key-signed deployment environment - despite having access to both funding or donated hosting to avoid this (Saivann immediately dropped from the project following this)

We were overpaying for the DDoS protection because we would get DDoS attacked very rarely (like once a year?), and when we did, the attacks were so strong that the protection usually wasn't adequate and the company would try to charge us even more. The key signing deployment made it difficult for the site to get changes, because the most recent commit had to be signed, and sometimes someone would forget that and the site would go a while of not being built. Many eyes are on this site, so any bad change would _very quickly_ be detected and removed.

> Cobra suggested it was OK for NY Agreement people to receive death threats and that there should be no mercy for them, and that assassination markets have been put into place historically for a reason (he later deleted these comments from #1836; John Newberry immediately dropped from the project)

The way I wrote that reply wasn't the best, that's why I deleted it. But I didn't say it was OK for anyone to get death threats, I said something along the lines of there being many crazy people in the community, and that death threats aren't unexpected when you have a community like ours, especially when money is concerned. By "no mercy" I obviously wasn't talking about it being OK to kill anyone, I meant that we as a community should not be merciful in our handling of the 2X CEOs, since people like John were advocating for dialogue, but I prefered to just remove these businesses from bitcoin.org and warn users against them.

> Soliciting a web development company in the Ethereum community, yesterday, to redesign and recode Bitcoin.org (essentially putting it into private control), create a new download page for Knots (alongside his announcement yesterday), without any formal due diligence or RFP initiative, much less else open feedback or public discussion amongst talented people who reside in our own community.

You really trying hard to smear me eh? The project was 3 phases, the first phase consisted of the designer creating 3 new landing page concepts for bitcoin.org. My plan was to then take these concepts and present them to the community and decide which ones they liked, and to proceed from there based on the response. Go look at the Slack meeting we had with her, go look at my emails, I made it explicitly clear how things would go. If anyone doesn't believe me, you can contact her yourself and ask her to publish the emails and logs of the slack meeting with me, her and Will (dribbble.com/nberowska).

> All of this combined, I'm concerned that he's basically become a corrupted, Denethor-like steward of Bitcoin.org at this point, bent on changing Bitcoin's PoW, with the first step in the execution of that strategy being a switch to Knots.

Ahh yes, trying to paint me as the next Bitcoin villain. Of course Knots is me and Luke's strategy to seize control and take over the network! So cute. I've been extremely radical about anything that breaks consensus with the current Bitcoin network. Where were you when I was writing statements condemning the 2X hard fork? I even discussed [removing Trezor because of their support for UASF](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1564). God forbid I try to promote anything other than Bitcoin Core.

@windsok Will changed it to a SegWit address, his own one, he's somehow able to do things like that since it's OK for him to merge straight to master, but not anyone else.

**Comment by xoviat** [comment]
Just dropping in, but since GitHub now signs merge commits with a GPG signature, checking the most recent commit for GitHub's GPG would de-facto require the pull request process.

**Comment by Cobra-Bitcoin** [comment]
Clearing some more FUD:

> myself included, about at least one of his personal accounts getting hacked

It was my Reddit account, not a big deal. I only use it to respond to FUD. The password was simple because I was in a rush when I created it, but who cares, it's just Reddit? I got it back eventually.

> create a new download page for Knots

It wasn't Knots specific. I'll quote what I said in the email for you:

> That sounds good. Let's proceed with phase 1 then. Also as an additional requirement, but for one of the landing pages, can you experiment with a notice + button at the top of the site with the text "Download Bitcoin" for use when there's a new version of the software released? Just want to see how it would look.

It would have been just a prominent link to the download page, similar to what bitcointalk.org does right now. Maybe alert whoever happens to be on the site and running the software that there's a new release, since things can get missed on Reddit or Twitter.

> much less else open feedback or public discussion amongst talented people who reside in our own community

She's in the cryptocurrency community. I don't really want to get into the habit of refusing to work with an extremely talented programmer or designer on projects just because they happen to be more involved in another cryptocurrency community. I also spoke to many different people, but her work was really good so I thought going ahead with phase 1 (concept designs + presentation to the community) at a very reasonable cost would be worth it.

**Comment by Cobra-Bitcoin** [comment]
> Soliciting a web development company in the Ethereum community, yesterday, to redesign and recode Bitcoin.org (essentially putting it into private control), create a new download page for Knots (alongside his announcement yesterday), without any formal due diligence or RFP initiative, much less else open feedback or public discussion amongst talented people who reside in our own community.

Fuck it. I'll just post an extract from the Slack meeting myself to show I was dedicated to involving the community in this, instead of letting Will spread FUD about me. Natalia or Will can post the entire thing themselves if they want, it shows I was **extremely clear** to involve the community: https://i.imgur.com/nrj7Ziu.png.

**Comment by kuzzmi** [comment]
I will not tag anybody specifically, consider this more like a general concern, just my few coins. 

Let's all agree that "openness" is one of the reasons why people trust Bitcoin. Let's all agree, that the website requires a redesign, because "it looks too dull, it doesn't look exciting". Another point that is quite difficult to argue with is that good intentions are not the same as following-up actions. 

Taking all of the above into account I was thinking that all the work related to the website has to be communicated publicly, and handled through a competition or with at least announced properly. I don't have much competence yet, nor any power, except for the right to express my own opinion, but wouldn't it be nice to at least mention any kind of intentions in a more open way? There were even a few GitHub issues raised about redesign, for example #1693.

> I was **extremely clear** to involve the community: https://i.imgur.com/nrj7Ziu.png.

From the provided screenshot it's clear for me that there were some intentions, which haven't resulted in any follow-up action.

**Comment by Cobra-Bitcoin** [comment]
> From the provided screenshot it's clear for me that there were some intentions, which haven't resulted in any follow-up action.

@kuzzmi That meeting was only a few days ago. Yesterday, Will told her to hold off on creating the 3 concepts. My plan was to take those concept designs, put them on an issue here, and start getting feedback. Work hasn't even started yet because Will is blocking it.

Redesigning bitcoin.org is a very large endeavour, and whoever does it would have to be OK with possibly not getting their design merged.  It's not a type of thing we can do through competition. That's why I contacted a professional and we could pay for her time to create excellent work (seriously look at her dribble) and we could **all** guide the design process through here. We've collected a ton of money through donations, so we should be using it to improve the site in ways like this. Will seems to be presenting things to make me appear extremely nefarious, when he himself was involved in the process.

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

I'm not the only one who thinks [with this latest incident](https://twitter.com/CobraBitcoin/status/933720123961171969) that you've [stepped well over the line](https://www.reddit.com/r/Bitcoin/comments/7f0cv0/bitcoinorg_plans_to_support_bitcoin_knots/).

Honestly, you shouldn't have SSH access to the server (I suggested several other people, other than myself). It's already a huge liability as it is that you have access to the domain. Especially after having at least one of your accounts hacked, regardless of what account it was. You have an elementary level of DevOps experience at best, and that's why a key-based deployment environment is a "hassle" for you, you also [make virtually no code contributions or improvements](https://github.com/Cobra-Bitcoin) to Bitcoin.org - or anywhere else in the Bitcoin space, for that matter.

Several talented contributors have reached their wits end as a result of your actions and have left the project this year. As far as I'm concerned, you're a steward of Bitcoin.org at best, not the owner, and you have more in common this past week with people who we as a community, just got done battling, than you do as someone who claims to be supporting "the one, true bitcoin," as you call it, on our side (lately it's starting to sound more like you're making CobraCoin to me, JBH).

You're frustrated because you don't have access to the funds so you can unilaterally hire a design/development company in the Ethereum space to carry out the plans for you that you don't have the skill to execute on yourself. You definitely were not going "to discuss this with the community" - until it was too late and money had already been spent.

Everyone should notice how so much of what you say hinges on what you were _going_ to do and your intentions, not what you actually _did_, and how you minimize everything you do like it's not a big deal. This is because you are manipulating them and trying to press forward with your own autocratic agenda.

If you have an expenditure you'd like to make, you can open an issue on the repository and discuss it with the community to see if they agree with you. @kuzzmi [noted one](https://github.com/bitcoin-dot-org/bitcoin.org/issues/1693) just now, about redesigning the site, above.

Until then, this is not open for discussion at this point in time. Full stop.

**Comment by Cobra-Bitcoin** [comment]
So.. a post full of FUD "CobraCoin" (seriously?), ad hominem, and personal attacks.

> You're frustrated because you don't have access to the funds so you can unilaterally hire a design/development company in the Ethereum space to carry out the plans for you that you don't have the skill to execute on yourself. You definitely were not going "to discuss this with the community" - until it was too late and money had already been spent.

Them being in the Ethereum space has nothing to do with the quality of their work. Unilaterally? You were literally in a meeting with me and the designer in question a few day ago! And yes, smart people usually hire other people to work on stuff they can't, I'm not a designer, and neither are many of the contributors to the site.

> Until then, this is not open for discussion at this point in time. Full stop.

Sorry sir. Please do forgive me. You're the boss. Now we can go back to the topic of making sure multiple parties are in control of the funds.

-----
Maybe @dooglus can also be involved as a multisig? I've heard he's a very trusted member of the community. Or maybe @gmaxwell?

**Comment by wbnns** [comment]
@Cobra-Bitcoin 

> Now we can go back to the topic of making sure multiple parties are in control of the funds.

Sure, we can do that as soon as we make sure multiple trusted parties are in control of Bitcoin.org.

**Comment by Cobra-Bitcoin** [comment]
> Sure, we can do that as soon as we make sure multiple trusted parties are in control of Bitcoin.org.

One of the reasons I'm not too annoyed about your revert is because @theymos didn't consent to the original Knots announcement, which I didn't expect, and we almost always don't do anything unless we both agree, but sometimes miscommunication happens. I'm not really the autocrat you're trying so hard to paint me as (I'll acknowledge sometimes I do make hasty decisions, but I always am open to being corrected).

Anyway, can you please stop derailing this topic. That literally has nothing to do with the discussion at hand. All you're doing is proving to the community that you'll only release the money to multisig under certain conditions that appease you. This is why I had to do things through direct merge, because you derail everything. We're just trying to talk about moving the donated money to a multisig address.

I'm asking you once again, kindly stay away unless you have something to contribute to the topic of this issue. Thank you.

**Comment by achow101** [comment]
I agree with @kuzzmi that this site should be developed in the open with open communication and discussion. It was mentioned earlier in this thread that there was discussion on an IRC channel and in a Slack group. Yet I see no mention in the README of said IRC channel or Slack group where anyone can join and participate in Bitcoin.org's development. At the very least plans for the future of Bitcoin.org should have an issue assigned to them and open to the public for discussion.

I also think that removing the requirement for the HEAD to have a PGP signature from someone on a list of trusted PGP keys was a bad idea. This requirement should stay, even if it is a hassle. It is a preventative measure; if an attacker were able to compromise Bitcoin.org and change things at will, it would look bad for Bitcoin.org even if it were noticed quickly and reverted. This would be bad in general and requiring PGP signed commits protects against that.

Additionally adding things to the website without a pull request should not be allowed whatsoever. This site is supposed to be a community developed site, so that means that not even the maintainers or domain administrators should be pushing changes directly to the site without a pull request or review from the community.

Back to the point at hand, I agree that Bitcoin.org's coins should be held in a multisig. At the same time Bitcoin.org itself should also be in the hands of multiple trusted parties where there is no one person can directly change the site without anyone else reviewing or providing input. I think that moving the funds to a multisig would be a first step to that, but many other things can be done as well simultaneously.

Lastly, I don't think that these types of arguments and discussions are good for the site and community in general. These disagreements make Bitcoin.org seem less reliable and trustworthy as even those maintaining the website do not agree as to what should be on the website. This is bad and should be avoided. 

Much of the recent issues have been between @Cobra-Bitcoin and @wbnns. I think it may be prudent for both of you to step down and hand off your responsibilities to someone else. Both of your behavior are certainly not helping this website and the arguments occurring here hurt Bitcoin.org's image.

**Comment by xoviat** [comment]
IMO punishing people for settling their differences in public just makes people hide their opinion for fear of being labeled controversial.

**Comment by Cobra-Bitcoin** [comment]
@achow101 Would be really great if you were part of the multisig! Would you be interested?

**Comment by achow101** [comment]
> @achow101 Would be really great if you were part of the multisig! Would you be interested?

Sure.

**Comment by Cobra-Bitcoin** [comment]
@achow101 Awesome!

So let's figure out who in the list below is interested, if you're in the list below, could you respond and state if you'd be up for being in the multisig? So far, we have @achow101, and I'm assuming @wbnns in the multisig. We need 3 more from the list below:

Possible multisig candidates: @theymos @TheBlueMatt @dooglus @gmaxwell @crwatkins. We could draft up a contract stating under which conditions the money can be spent. Something even as simple as the majority of the treasurers agreeing that the expenditure is necessary, and that the expenditure has been justified in public discussion beforehand and there's been no reasonable arguments against it.

**Comment by luke-jr** [comment]
Assuming that @wbnns cooperates with a reasonable multisig proposal, I suggest that he should himself at the very least be a candidate for a signer, considering the ample evidence following from his cooperation that he can be trusted with the funds even without cosigners.

**Comment by Cobra-Bitcoin** [comment]
If we can't get enough people for 3 of 5, we can just do 2 of 3, with @wbnns @achow101 and whoever else would be interested.

@luke-jr I'm assuming he wants to be a signer, but haven't had any confirmation. I'm counting him as one of the people ready to be in the multisig, unless he objects.

**Comment by wbnns** [comment]
I agree multisig is a good idea (and happy to be a part of it), however, disagree that it should just be comprised of whoever. I think this an ideal opportunity to work together as a team and simultaneously improve security/redundancy across the board.

At least a couple of qualified and trusted people who can be reached via phone by maintainers/active contributors should have access to the hosting server and domain. Almost 10,000,000 people have visited Bitcoin.org in the last three months - we have a responsibility to ensure that there is a reliable, redundant and trusted infrastructure in place to serve them, as best as we can.

One person shouldn't autonomously be deciding to announce to them that Knots is going to replace Core in the download area (a independent section of the site that's gotten millions of visits this year), or if a key-based deployment environment is a bad idea.

**Comment by MrHash** [comment]
Hey all, what's the status of this? It's an important political issue to resolve peacefully so the site can progress.
