### ISSUE TITLE
New glossary term suggestion: token

### ISSUE THREAD

**Issue by Richouser** [bitcoin-dot-org/bitcoin.org#2001]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

How does it differ from a coin, and blockchain application

**Comment by Tusharchoudhary** [comment]
Hi how can i attempt to solve this ?

**Comment by Richouser** [comment]
Define the difference between a crypto coin or alt coin, and a crypto token.

Thank you.
On Dec 25, 2017, at 9:52 AM, Tushar Choudhary <notifications@github.com> wrote:

> Hi how can i attempt to solve this ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Richard and Dyana Houser
Santa Barbara Art Frame Co.
19 West Gutierrez St.
Santa Barbara, CA 93101
805 966-1300

http://www.sbartframeco.com
richard@sbartframeco.com

**Comment by Tusharchoudhary** [comment]
Tokens can be created by any projects, startups or business.
Depending upon the need their functions and value can be programmed.
By ownership of a token the creator promises a contract to be fulfilled in exchange of the token.

**Tokens abstract the qualities of a coin, or crpyto-currency.**
But instead of using their own native blockchain to maintain trust they depend on some other existing  blockchain.
This removes the need to create new infrastructure and benefits the native blockchain by increasing usage. 
Tokens are initially distributed during ICOs for exchange of digital currencies.
And later can be exchanged between anyone in the native blockchain.
The trust is maintained as token transactions can be viewed on the public ledger.
Tokens are to **ICO** as what shares are to IPOs.
Difference b/w coin and token-
**Coins are currencies with their own separate blockchains while tokens operate on top of a blockchain that facilitates the creation of decentralized applications.**

**Comment by Tusharchoudhary** [comment]
how may i further improve this ?

**Comment by Richouser** [comment]
Dear Tushar,

For the glossary, this definition is very adequate, and I would add it as the “token" definition.
Let me know if I can be of further assistance.

Best,  Richard

Coins are currencies with their own separate block chains while tokens operate on top of a blockchain that facilitates the creation of decentralized applications.


On Dec 29, 2017, at 8:13 PM, Tushar Choudhary <notifications@github.com> wrote:

> how may i further improve this ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Richard and Dyana Houser
Santa Barbara Art Frame Co.
19 West Gutierrez St.
Santa Barbara, CA 93101
805 966-1300

http://www.sbartframeco.com
richard@sbartframeco.com

**Comment by Tusharchoudhary** [comment]
I want to contribute more, if possible could you guide me with the process of adding the definition, I ll like to do it myself.

**Comment by Richouser** [comment]
Tushar,

I am sorry, I do not know how to do this as I am only a student of cryptos and just beginning to learn.  That is why I was reading the glossary and noticed the term token was not listed, and submitted a new term suggestion.

Best,
Richard

**Comment by RandyMcMillan** [comment]
This looks resolved. Close.
