### ISSUE TITLE
Subpages Outline for Redesign

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2138]
@natiwa

Here's an initial [subpages outline](https://docs.google.com/spreadsheets/d/1wrmYP5dePSOaatbTD2TIk9MKcIkJWHlU3j9K_6RzRFU/edit?usp=sharing) for extending the Version 3 design.

They are in descending order starting with the pages that receive the most website visitors.

Let's plan to discuss during our progress meeting tomorrow. If you have any questions or comments, feel free to add them to the spreadsheet, or post them here under this issue (others who are reading this, please feel free to do the same).

**Comment by natiwa** [comment]
Hi,
I have grouped all subpages by the Layout types. 
[Link to the spreadsheet](https://docs.google.com/spreadsheets/d/17ncFqPXjiFlyA3i2rk3mq-kHuxpl_DqafhqjZPjHDY8/edit?usp=sharing)

We will have 6 layout templates and 14 Individual layouts. 
Let me know what you think.

**Comment by wbnns** [comment]
@natiwa 

Great, thanks. I think we may be able to consolidate these a bit further and have less individual layouts.  Let me review and I'll follow-up here.

**Comment by natiwa** [comment]
Sure. Some of them are still quite similar.

**Comment by natiwa** [comment]
My further suggestions:
- [https://bitcoin.org/en/development](https://bitcoin.org/en/development) and [https://bitcoin.org/en/about-us could](https://bitcoin.org/en/about-us) could be in the "Layout template 5" group
- [https://bitcoin.org/en/innovation](https://bitcoin.org/en/innovation) could be in the "Layout template 1" group 
- [https://bitcoin.org/en/developer-glossary](https://bitcoin.org/en/developer-glossary) could be in the "Layout template 2" group 
- [https://bitcoin.org/en/secure-your-wallet](https://bitcoin.org/en/secure-your-wallet) is very similar to the Layout Template 5

**Comment by Cobra-Bitcoin** [comment]
Let's not forget the download page which will obviously need it's own modern looking design: https://bitcoin.org/en/download. 

The buy bitcoin page looks so empty, could we look into ways to make it look a bit more filled out? We can have a grid with a few exchanges and a "See more" button which links to the exchanges page, and under the "Discover people selling Bitcoin in your community" heading we can have a text field where the user enters their country, and then a "Find" button which automatically redirects them to listings on localbitcoins for that particular country. Content wise for that page, we should add a a few paragraphs about the risks involved in buying Bitcoin (erratic price swings) and how much users can save by buying through bank wire, instead of credit card (but these are more issues around content so don't worry about them for now).

Regarding the getting started page, right now it looks pretty... dull. When we're making a new design for this page we should make it seem as exciting as we can, let's try to have lots of little icons and have an improved flow. It shouldn't just be all text and buttons, but also include icons and arrows and it should feel somewhat interactive. And you'll notice that the getting started page is split into two parts, the "How to use Bitcoin" section and the "How to accept Bitcoin" section, let's try to make this split even more clearer and emphasised in the new design.

Don't be afraid to take risks, it's a redesign so we want the pages to look really different. Sometimes in redesign projects there's a tendency to just put a fresh "skin" on top of existing content, instead of restructuring the content completely to maximize the UX and make it feel fresh. For example with the choose your wallet page, visiting it on mobile can be annoying, so it would be good if we completely changed this page and rethought how to best present the content to the user.

I don't think we'll need to see responsive versions of these subpage designs except for a few key pages, the rest we can just figure out during development. The following would be ones I would be keen to see the responsive versions for though, but only mobile, let's not worry about tablet:

- Getting started
- Choose your wallet
- Wallet page

Looking forward to seeing what you produce @natiwa!

**Comment by natiwa** [comment]
Thanks @Cobra-Bitcoin 

I have added the https://bitcoin.org/en/download to the spreadsheet. 

On the previous weekly meeting, we were discussed to not changing too much on the subpages because of the SEO, but of course, I will change the layout to make it more user-friendly and intuitive.

@wbnns Let me know if you want to group those subpages in a different way. So I could prepare the Estimation.

**Comment by Cobra-Bitcoin** [comment]
@natiwa We wouldn't be changing the content much on the important pages, just alter how it's presented like we did with the homepage design.

SEO would only be an issue if we broke apart existing content on to different pages. As long as Google's crawler is reading the same content in more or less the same structure, then we're fine. Though we do need to be careful with some pages, but it's definitely possible to redesign it thoroughly without compromising SEO.

**Comment by natiwa** [comment]
@Cobra-Bitcoin Ok. Thanks :)

**Comment by wbnns** [comment]
@natiwa 

Thanks a bunch. Let's go ahead and get started with the new subpage design for the [Getting Started](https://bitcoin.org/en/getting-started) page to start, since that's the most visited subpage. From there, let's plan to move into the `Choose Your Wallet` page, and then start rolling through these other pages. I think we'll find that we'll be able to consolidate even further as we start knocking things out.

Please post the preview for the Getting Started page in #2139 when it's ready.

**Comment by wbnns** [comment]
@natiwa 

As you're working on the Getting Started page, can you please go ahead and also start on the wireframe for the Choose Your Wallet section of the site (and also the relevant subpages - e.g. wallet categories and individual wallet listings)? You can post the progress in #2139, like you did with the Getting Started page.
