### ISSUE TITLE
Adding the https://AbolishTheBitlicense.org to the Learning Ressources

### ISSUE THREAD

**Issue by theochino** [bitcoin-dot-org/bitcoin.org#2146]
As Bitcoin is being attacked, this resources is about pushing back with knowledge and facts.

I have included all the videos that show the technology without using a computer (to show that it is not required to have a computer to mine, create a private key, send a transaction.)

I also including all the trial documents that exist and all the legislative hearing I can find on video and it's also a resource for those going to see their legislators to explain bitcoin and lawyers to understand bitcoin and to figure out whether or not it is relevant to their case.

The website is **AbolishTheBitlicence.org**

Theo

**Comment by wbnns** [comment]
Closing this as the site appears to be down.

**Comment by theochino** [comment]
The site is not down.

**Comment by theochino** [comment]
https://www.abolishthebitlicense.org

**Comment by wbnns** [comment]
@theochino Thanks for the clarification, it looks like the problem was that there was a typo in the issue you opened, which is why I was unable to load your website:

![image](https://user-images.githubusercontent.com/1130872/39935482-5e3390f2-5506-11e8-8cb9-5f3c52e0f45b.png)

Another issue is that the current learning resources provide broad, high-level information about how Bitcoin works. Your website is very specific with regard to legislation that only applies to a subset of users in the state of New York.

Perhaps at some point in the future we could have some sort of area on the site that contains a lot of content pertaining to laws and regulations by country. Maybe some kind of deeper and more content rich synopsis that [Wikipedia](https://en.wikipedia.org/wiki/Legality_of_bitcoin_by_country_or_territory) has (along with detailed information by state and/or province in various countries, with links to your work to abolish the Bitlicense).

If others disagree or have any feedback, please feel free to add to this issue and I'll reopen it.
