### ISSUE TITLE
Estimate Fee and Estimate Smart Fee in developer reference

### ISSUE THREAD

**Issue by rbndg** [bitcoin-dot-org/bitcoin.org#2219]
[Bounty](https://github.com/bitcoin-dot-org/bitcoin.org#earn-bitcoin-for-contributing): **7,000 bits / ~$50 USD**

I believe the deprecation notice for estimateFee is missing in the documentation
https://bitcoin.org/en/developer-reference#estimatefee

Also estimateSmartFee doesn't seem to be documented at all?

**Comment by StemRoot** [comment]
I need to close all my wallets can you since you have the authority close them and put in to one or do I need to push a notification


Sent from my Sprint Samsung Galaxy S8+.
-------- Original message --------From: rbndg <notifications@github.com> Date: 3/18/18  6:31 PM  (GMT-08:00) To: "bitcoin-dot-org/bitcoin.org" <bitcoin.org@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [bitcoin-dot-org/bitcoin.org] Estimate Fee and Estimate Smart Fee in
  developer reference (#2219) 
I believe the deprecation notice for estimateFee is missing in the documentation

https://bitcoin.org/en/developer-reference#estimatefee
Also estimateSmartFee doesn't seem to be documented at all?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bitcoin-dot-org/bitcoin.org","title":"bitcoin-dot-org/bitcoin.org","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bitcoin-dot-org/bitcoin.org"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Estimate Fee and Estimate Smart Fee in developer reference (#2219)"}],"action":{"name":"View Issue","url":"https://github.com/bitcoin-dot-org/bitcoin.org/issues/2219"}}}

**Comment by rbndg** [comment]
not sure what you're talking about

**Comment by eaguilera23** [comment]
estimateSmartFee was not documented :(
