### ISSUE TITLE
Blacksburg Blockchain Symposium

### ISSUE THREAD

**Issue by franzisimone** [bitcoin-dot-org/bitcoin.org#2253]
- date: 2018-04-20
      title: "Blacksburg Blockchain Symposium"
      venue: "Lyric Theatre"
      address: "135 College Ave"
      city: "Blacksburg"
      country: "USA"
      link: "www.bburg-blockchain.io"

**Comment by twolmarans** [comment]
Hey,

As we want to standardize this;

Q: Is this a Bitcoin event?
A: No

Q: Is there a talk focused exclusively on a Bitcoin topic?
A: No

Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?
A: No, it seems to be a general blockchain event

Result: I think that this could be listed, but since I'm new here, I'm not sure if it would fit the bill due to it not being Bitcoin (or any other coin) specific

**Comment by franzisimone** [comment]
Hi,

No, it is not a bitcoin focused event and there won't be a talk focused exclusively on bitcoin.

However, regarding question three: there is going to be a panel and a keynote address dedicated on cryptocurrencies and regulation. The goal is to go beyond the buzz, analyze and discuss the implications of these financial instrument.
