### ISSUE TITLE
Russia ICO Show

### ISSUE THREAD

**Issue by AlexIDACB** [bitcoin-dot-org/bitcoin.org#2274]
- date: 2018-04-26
      title: "Russia ICO Show"
      venue: "RENAISSANCE MOSCOW MONARCH CENTRE HOTEL"
      address: "31A bld. 1 Leningradsky Prospect "
      city: "Moscow"
      country: "Russia"
      link: "http://rico.wbcsummit.org/"

**Comment by beyourseff** [comment]
#2271 #2272 #2273 and this one all focus on ICO's. I do not recommend having any of them added to the events page.

**Comment by beyourseff** [comment]
Thanks for the reply @AlexIDACB - I got confused since the page has a big 'World ICO Show' banner.

After checking the schedule, it seems the entirety of day 2 is focused on ICO's. The topics discussed on day 1 don't quite relate to Bitoin and/or its underlying technology. There's also an ICO pitch on day 1.

I'll leave it to @wbbs to decide since I'm only making a suggestion. He'll be the one who decides whether or not it'll be suitable for inclusion :)

**Comment by CosmicHemorroid** [comment]
@beyourseff you are doing God's work. Thank you.
