### ISSUE TITLE
Blockchain: Rethink Trust

### ISSUE THREAD

**Issue by vitaliy-kurat** [bitcoin-dot-org/bitcoin.org#2290]
- date: 2018-06-29
      title: "Blockchain: Rethink Trust"
      venue: "Beurs van Berlage"
      address: "Damrak 243, 1012 ZJ "
      city: "Amsterdam"
      country: "Netherlands"
      link: "https://rethinktrust.org/"

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: Not really, moreso 'blockchain technology'.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: Doesn't seem to be the case.

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Doesn't seem to be the case.

**Notes:** Media partners aren't quite reputable. The organizers seem to have a financial incentive to push the 'blockchain technology' onto the attendees since they're a blockchain consulting and development company. All in all, this gets a narrow pass from me.

Result: **In my opinion this event could be listed on Bitcoin.org based on the above.**
