### ISSUE TITLE
Ten year anniversary 

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/bitcoin.org#2294]
In 4 months, Bitcoin.org will be ten years old.

I was thinking we should celebrate this somehow on the day (18th of August), since ten years is a pretty big deal, any ideas on what we could do? I was thinking we replace the homepage with a "Letter to Satoshi" honouring him somehow, along with all the other contributors over the years.

We can focus on a handful of top contributors, explain what they've worked on, thank them for their efforts, and possibly list a Bitcoin donation address for them and encourage the community to donate to them.

Thoughts?

**Comment by beyourseff** [comment]
Good idea! 

I think instead of encouraging the community to donate to specific top contributors, we could instead select a given charity for which we will raise funds. Have a 24-hour time frame in which all donations to a given Bitcoin address will be accumulated and at the end be sent to a charity of the communities' choosing. 

This could be made an annual thing where each year we select a charity we donate to, call it 'Satoshi's Gift' :)
