### ISSUE TITLE
Blockchain & Bitcoin Conference Canada

### ISSUE THREAD

**Issue by canadablockchainhub** [bitcoin-dot-org/bitcoin.org#2303]
- date: 2018-04-24
      title: "Blockchain & Bitcoin Super Conference - Canada"
      venue: "Kitchener - Waterloo Innovation District"
      address: "32 Weber Street West"
      city: "Kitchener"
      country: "Canada"
      link: "https://blockchainsuperconference.com/"

<img width="887" alt="bcsc_titlepage2" src="https://user-images.githubusercontent.com/38699412/39201287-8fbc151a-47bc-11e8-8750-a19334dd2749.png">

**Comment by beyourseff** [comment]
Hello there, 
I've taken the time to check this event and assess if it's suitable for inclusion on the Bitcoin.org events page.

To do this I've answered the below three questions:

**Q: Is this a Bitcoin event?**
A: I'd say no, not really.

**Q: Is there a talk focused exclusively on a Bitcoin topic?**
A: There's 3 talks it seems

**Q: Will there be talks regarding ICO's and/or altcoins? If so, how much time will be dedicated to them in total?**
A: Yes, there's a number of ICO pitches which in total take up more time than the short Bitcoin talks.

**Notes:** I'm leaning towards saying no due to the ICO pitches taking up more than double the time than Bitcoin-focused talks. It seems to me the event is therefore more centred towards ICO's and getting people to invest in them rather than educating the attendees about Bitcoin and/or its underlying technology.

Result: **In my opinion this event should NOT be listed on Bitcoin.org based on the above.**

**Comment by nplusnetworks** [comment]
Hello,

Thank you for taking the time to review our event.

Please let us add more clarification. 

Our event to is primarily focused on bitcoin and the underlying technology and is one of the most bitcoin centric events that is happening. The main purpose of the event is to promote awareness and education and we've made very specific bitcoin related talks and seminars because we've found those to be lacking in other events.  

Most of the event will revolve around explaining, research and development, and workshops about bitcoin and blockchain technology from industry experts.

We have an extensive portion discussing the history of crypto and the development of digital currencies from 1983 onwards reviewing the works, papers and contributions of people such as David Chaum, Nick Szabo, Hal Fineney, Adam Back, Wei Dai and others that layed the foundation for Bitcoin.

We will have an indepth review of the Satoshi Nakamoto's Bitcoin White Paper. 

We are also having hands on workshops and tutorials on bitcoin and how to make blockchains.

This event is not to promote people investing in ICO's but is actually focuses on promoting awareness and educating the attendees about Bitcoin and/or its underlying technology.  Consequently to reflect this ICO's have been removed from the schedule and we will be giving this allotment to the presentation of research papers.

We've updated the schedule to be more clear on this:

https://blockchainsuperconference.com/schedule/

Considering this would you please list the event on your website as the main intention is to educate and promote awareness regarding bitcoin and blockchain technology.

**Comment by canadablockchainhub** [comment]
Hello Will,We are interested in doing an event that is Bitcoin and blockchain focused and would be appropriate interest for the Bitcoin community and acceptable for bitcoin.org events listing. We updated our event to reflect this. Would you please let me know what else we could do to fit your guidelines. ThanksKapleyOn May 3, 2018 6:59 PM, Will Binns <notifications@github.com> wrote:Closed #2303.
