### ISSUE TITLE
Remove price feed from redesign

### ISSUE THREAD

**Issue by maaku** [bitcoin-dot-org/bitcoin.org#2332]
Bitcoin is a peer to peer payment network, not an investment asset, and bitcoin.org should not imply otherwise. People go to bitcoin.org to learn about bitcoin, not to invest their money. Please consider removing the price feed from the redesign.

**Comment by harding** [comment]
As a reminder to the maintainers, this issue was raised earlier and then closed without comment: https://github.com/bitcoin-dot-org/bitcoin.org/issues/2105#issuecomment-361450978

**Comment by wbnns** [comment]
@maaku Thanks for the feedback. @harding Apologies for the misunderstanding - the issue you're referencing (#2105) was to select a new homepage design. I closed it after the community vote was held, when the design with the most votes was selected.

I'll leave this one open.

**Comment by Cobra-Bitcoin** [comment]
The more I think about it, the more it makes sense to remove it. Not so good if the first thing newbies see on the site is the price.

**Comment by crwatkins** [comment]
I'm good with removing it.

**Comment by maaku** [comment]
There are limitless places on the internet to get the bitcoin price for people who want to know. Bitcoin.org is *not* the place to provide such information. It's not the point of the website; it's not the point of bitcoin. Even more so for charts and analysis. If you think the point of bitcoin is its price relationship with USD, you are very much missing the point, and educating that difference is what bitcoin.org is supposed to be doing.

**Comment by wbnns** [comment]
I don't think that's the point but I do think one of the things that makes Bitcoin great is that it be different things to different people. For many people it's an alternative investment vehicle, and the way they first find out about it is by hearing about the price, and then typing "bitcoin" into a search engine.

We can respect that and try to be helpful alongside all of the other great resources on the site, or we can ignore that and let them go somewhere else where another site is going to tell them what the point of bitcoin is.

**Comment by harding** [comment]
> Ignoring what users want risks us being supplanted by others who give it to them.

Ignoring some of what people want allows you to focus on the things they want that you can excel at providing.  It seems unlikely to me that Bitcoin.org will ever be the best site at providing price charts and commentary, but the site (IMO) is already the best at providing solid educational resources about Bitcoin that are free from the hype and promotion (or lies and FUD) found on other sites.  By focusing the site on what it's great at, I think it's much more likely to stay relevant than it will by providing the same features found elsewhere.

In addition, looking at the preview site, I note that the price ticker is supported by loading Javascript from the site BitcoinAverage.com.  This discloses information about every Bitcoin.org pageview to the operators of that site and may allow them to arbitrarily change content displayed on Bitcoin.org for visitors, both of which seem undesirable to me.

**Comment by wbnns** [comment]
Regarding loading JS, the [function](https://github.com/bitcoin-dot-org/bitcoin.org/blob/redesign/js/main.js#L471) is only able to grab the following [price data returned in JSON](https://apiv2.bitcoinaverage.com/indices/global/ticker/short?crypto=BTC&fiat=USD) from BitcoinAverage and round it to the nearest cent - it doesn't work, otherwise. This isn't a new function and has already been in use for many months on the current website, to help people make donations to the nearest whole-dollar.

Since the website has millions of visitors, I feel like this should be a data-driven decision rather than something based upon conjecture between 5 people.

A couple of suggestions:
+ Do a poll to see if users would like to be able to see the bitcoin price on Bitcoin.org
+ Look at Google Analytics to see what are the most-viewed pages to determine if price might be something people are interested in

Let me know what you guys think.

**Comment by theymos** [comment]
Agreed, that's something that I didn't like much about the new design. While some people might be mostly interested in the price, and that's OK, I think that *bitcoin.org* should focus on the aspects of Bitcoin that go beyond price.

**Comment by harding** [comment]
> the function is only able to grab price data returned in JSON from BitcoinAverage and round it to the nearest cent - it doesn't work, otherwise.

I'm glad to hear that.

> This isn't a new function and has already been in use for many months on the current website, to help people make donations to the nearest whole-dollar.

I think you mean that it *was* in use.  It was part of the donation banner ad, which has been disabled in 84d753c357942cd0cc1a9d20ea1f9d03e791ff1f (late Sept 2017).  Running my browser in network profile mode, it doesn't attempt to load any data from BitcoinAverage.com on the current site.  Even when it was enabled, the function was only run when the function `openDonationModal()` was called.

This seemed much less bad to me for privacy, as BitcoinAverage.com wasn't receiving information about every pageview, but only the cases where the person indicated they wanted to donate to Bitcoin.org.  On the new site, I assume that they'll receive a call for every pageview.

I know most websites don't consider leaking visitor data to third parties to be bad, and it's worth noting that Bitcoin.org does currently send all of that information to Google via Analytics, but it still seems undesirable to me to disclose visitor data from a popular Bitcoin site in order to add a minor feature (or anti-feature).

**Comment by wbnns** [comment]
Ok, dropped with 0a7e58cc.
