### ISSUE TITLE
Redesign All Wallets tab returns 404 on preview

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2402]
On the current preview, go to the home page and select ```Choose Your Wallet```.
It lands on the ```All Wallets``` tab.  Select the ```All Wallets``` (redundantly) or go to a different tab and come back.   Get 404 error.

**Comment by Cobra-Bitcoin** [comment]
This needs to be fixed. But I think we need to get rid of the reloading. If I'm on the "All Wallets" tab, and I click on the "Web" tab, why is the reload to a new page necessary if all the information is already on the existing page, and we just need to filter out the non-web wallets? Just makes everything much slower, for no real reason, when we can filter between the wallets client side.

**Comment by Cobra-Bitcoin** [comment]
We already seem to be doing this client side filtering on the wallet menu when inside a specific wallet: https://bitcoin.cryptopelago.com/en/wallets/desktop/windows/electrum/. So it should be simple to transfer this logic to the main choose your wallet page.

**Comment by wbnns** [comment]
This has been fixed by #2403.

The reason the page reloads is for SEO purposes - each page is unique and is indexed by search engines. For example, we're the first and second results (after paid ads) for "android bitcoin wallet" and "bitcoin wallet for android":

![image](https://user-images.githubusercontent.com/1130872/40690847-3e777ea4-6366-11e8-8d10-5ba6fbb43e56.png)
