### ISSUE TITLE
Coinbase, BitPay, Blockchain.info missing

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin-dot-org/bitcoin.org#2426]
I would like to hear the justification for this. How does the removal of these three huge Bitcoin access points serve new users, spread adoption of Bitcoin, and disrupt the legacy global financial system? What is the new criteria for being ignored by this critical web portal?

**Comment by achow101** [comment]
blockchain.info was [removed a long time ago](https://github.com/bitcoin-dot-org/bitcoin.org/pull/663) after a re-review of their compliance to bitcoin.org's listing criteria.

Coinbase and BitPay [were](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1836) [removed](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1752) during the Segwit2x debacle last year (along with several other companies that supported the fork) and have not yet been reinstated probably because people forgot.

Perhaps it is time to reinstate these companies and their wallets on bitcoin.org, however a review of their compliance to our policies is necessary.

**Comment by wbnns** [comment]
This is being discussed in #2577.
