### ISSUE TITLE
A guide how to create flags of countries for list of bitcoin exchanges.

### ISSUE THREAD

**Issue by derwustenfuchs** [bitcoin-dot-org/bitcoin.org#2476]
Hello, I'd like to add our exchange market to bitcoin.org but I cannot understand how to create a flag of country with the same properties as the rest of .svg flags on bitcoin.org. I've downloaded Sketch app and I have a flag of country from wikipedia, but I don't know how to change it to suit website's scale of flags.

**Comment by wbnns** [comment]
@derwustenfuchs 

Hello, [this Sketch file](https://mega.nz/#!qnYCXAbI!-91DABUv9Yxbj6Vgvci6yw4fjJw9oClJzav7QVF1xHU) was prepared to create a flag icon in the proper size for the website. You would need to put a graphic of the flag in the "Place flag here", like so:

![image](https://user-images.githubusercontent.com/1130872/46955083-5bdfdb00-d092-11e8-9c8f-59f7817194f6.png)

And adjust the width and height if needed:

![image](https://user-images.githubusercontent.com/1130872/46955095-669a7000-d092-11e8-864c-cbfb7b12e00f.png)

Once you've done this, the flag is ready for export so that it can be added to the site.
