### ISSUE TITLE
"Buy Bitcoin" button is broken for multiple translations

### ISSUE THREAD

**Issue by StayCoolDK** [bitcoin-dot-org/bitcoin.org#2569]
Hello guys. How come https://bitcoin.org/da/buy is broken, alongside many other translations of this page? Is this due to the addition of the paxful sponsorship? If so i think it should be removed, if it breaks important functionality of the site. It was working flawlessly before this sponsorship integration. The "Buy Bitcoin" button is also the only element on the entire site that is not translated.

**Comment by harding** [comment]
These cases are usually handled with the `case` statement and `page.lang` as described here: https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/assisting-with-translations.md#update-english-strings

**Comment by wbnns** [comment]
@StayCoolDK Hello, thanks for discovering this bug and reporting the issue. The reason the page isn't loading is because it hasn't been translated yet. Serbian, German and Chinese do not have this issue because they have been recently updated.

I've opened #2570 so that people can still load the page in English if they'd like. As each language gets updated, the redirect will be removed so that it displays natively.

**Comment by wbnns** [comment]
Ok, merged #2570 so that users don't think that the button is broken and nothing happens when they click/touch it (if the page isn't available in their language).

Also just wanted to mention an alternative - we could supersede the change with a conditional on the home page template that doesn't show the button if the page isn't available in the language.

If we go that route, might be good to get feedback from additional people who speak a language other than English as their first language to see if they'd like the content available or not (but that's just my two cents).
