### ISSUE TITLE
Automating the event process

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/Bitcoin.org#2646]
Currently we have it so events are submitted as issues here, and then they have to be reviewed within Github, and once that's done, the maintainer has to manually update the events YML.

I was thinking we could improve that workflow by doing the following:

- We have an event submission page located at 'events.bitcoin.org' with a basic form collecting all the necessary information about the event (title, date, website link, etc)
- A list of pending submitted events are displayed at an admin portal located at 'events.bitcoin.org/manage' and allows the admin to approve/deny any events
- If an event is accepted, it gets added to the accepted events pool, and if denied, it gets removed from the database and submitter gets an email with the reason for rejection
- Once a week we have an 'event bot' merge accepted events automatically into master, the bot will [have permissions](https://platform.github.community/t/single-file-write-access/374/4) to only be able to modify the "_events.yml" file

This would save us so much time and clean things up in our issue tracker immensely. I find it pretty annoying when I get an email from Github about a new issue on bitcoin.org, and then find out it's just someone submitting an event. I've already written some of the basic code in Node.js / Express, but wanted to see what others thought before proceeding further. At most it would take a few days to code, and then maybe a bit more to test and verify everything works nicely.

Thoughts? In particular I'm curious what @applesolbrilla thinks about doing it through this process since she's been doing great work reviewing a lot of the events lately.

**Comment by Cobra-Bitcoin** [comment]
Really want to know what @applesolbrilla thinks about this so I can move this forward. I can probably have something ready by the end of this week. Much of the work is already done.

The event spam is getting pretty bad on our issue tracker :(

**Comment by wbnns** [comment]
@Cobra-Bitcoin Heya, I employ @applesolbrilla to assist me and one of the things she does is review the events. Yes, it would be nice if we could have more signal on the repository by filtering out events, however, no sure if we need a system dedicated to just events management. That said, was thinking about this and it seems like we could potentially use the same type of set up to allow people to submit Bitcoin-related jobs that we could then post on the website (which would also take care of #2524) for people to browse.

There would probably be a lot more jobs (especially spammy ones that might need to be filtered out). Basically, instead of what you're suggesting adding an event, it would add jobs / opportunities people could browse to a page dedicated to earning / working for bitcoin.

What do you think?

**Comment by harding** [comment]
Note: you could probably just create a separate repository under the github.com/bitcoin-dot-org organization that just handles events (and is just a short README.md), and then just update the links for submitting an event issue to point to that repository.  Otherwise, you could keep the workflow exactly the same as it is now.  Only people interested in events would follow that other repository (or people like @Cobra-Bitcoin who might need to follow it could at least set up an email filter to redirect its issues to a separate folder).

**Comment by Cobra-Bitcoin** [comment]
@wbnns Good idea, I think it would be really good for that function actually. I'll get it done.

Thanks @harding for the tip, I think having a separate repo would be good too. Basically I think an issue tracker should function as an issue tracker, but right now all these events clutter it up. There also doesn't seem to be any way to filter [this page](https://github.com/bitcoin-dot-org/bitcoin.org/issues) to do something like "show me all the issues but *not* ones labelled with 'events').

**Comment by harding** [comment]
> There also doesn't seem to be any way to filter this page to do something like "show me all the issues but not ones labelled with 'events').

To negate a search criteria, prefix a `-` to the term you want to negate; e.g. `-label:Events is:open`
