### ISSUE TITLE
MPWR Crypto Mining Summit 2019

### ISSUE THREAD

**Issue by colinnebocat** [bitcoin-dot-org/bitcoin.org#2796]
- date: 2019-03-12
      title: "MPWR Crypto Mining Summit 2019"
      venue: "Pan Pacific Hotel"
      address: "300 - 999 CANADA PLACE, VANCOUVER, BC V6C 3B5"
      city: "Vancouver"
      country: "Canada"
      link: "https://www.mpwrsummit.ca/"

**Comment by khendraw** [comment]
- Is this event specifically related to Bitcoin? No
- Is there a talk focused exclusively on Bitcoin? No
- Are the majority of talks focused on ICOs and/or other digital currencies? No
I don't think this event should be added to Bitcoin.org

**Comment by colinnebocat** [comment]
Hi, can you please delete this issue? I don't want it showing on my profile.

**Comment by wbnns** [comment]
@colinnebocat 

Hello, rather than delete the issue and our record of it, if you'd prefer not to be associated with it anymore in the context of your GitHub account, you could:

1. Change the email address associated with your GitHub account to something else
2. Change your GitHub username
3. Remove the customization from your GitHub profile (e.g. profile picture, name, bio, location, company, etc.)
4. Create a new GitHub account with your desired email address and username.
5. Customize the new GitHub account to your liking.

The new GitHub account would show no association with the issue.

Hope that helps.

**Comment by colinnebocat** [comment]
Um, I think you should just delete it rather than me delete my whole account.
