### ISSUE TITLE
Copay for Android not on Google Play

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2843]
@matiu It seems that Copay is [no longer](https://github.com/bitpay/copay/issues/9423) on Google Play.  Can you explain why this is?

Would you prefer to remove Android from Copay support on bitcoin.org or fix the broken link on copay.io to Google Play or do you have another suggestion?

**Comment by matiu** [comment]
Hi. Because of google play policies we cannt have Copay and Bitpay Wallet
wallets on the Play Store together so we are keeping Bitpay Wallet.

I suggest updating the link to Bitpay Wallet app, which is build from
exactly the same source, but with Bitpay Card integration turn on.
Instructions to build bitpay wallet app are also shown on the Github repo
Readme.

The link for the play store is:
https://play.google.com/store/apps/details?id=com.bitpay.wallet

**Comment by crwatkins** [comment]
@matiu The broken link is actually on copay.io (that bitcoin.org points to).    Do you want to fix that link?  Perhaps to point to your own .apk in your GitHub releases?  Any other ideas?

**Comment by crwatkins** [comment]
This is due to Google policies.  The wallet is still available on GitHub.

**Comment by maxwellmons** [comment]
The main link that people use is still broken. Should this still be closed?
