### ISSUE TITLE
ArcBit current status

### ISSUE THREAD

**Issue by crwatkins** [bitcoin-dot-org/bitcoin.org#2845]
@stequald Is ArcBit currently being maintained?  I can't reach https://www.arcbit.io, there hasn't been a commit for over a year, our links to the Chrome extension are broken, and there are numerous unanswered complaints/bad reviews on Google Play.

I installed from Google Play to an Android phone running Oreo and no receive addresses appear.

Should we remove the listing or do you have other suggestions?

**Comment by stequald** [comment]
He Craig,

ArcBit for Android is no longer being maintain. You can remove the android option from bitcoin.orgs listing.

Best,
Tim

**Comment by crwatkins** [comment]
Hey Tim,

OK on the Android.  What about the Chrome links?  They are broken too, both from bitcoin.org and the promotion links from within the iOS app.  Also arcbit.io isn't working for me.

**Comment by stequald** [comment]
Yeah, I'm no longer keeping the site up. If that's a problem for
bitcoin,.org you can remove ArcBit from being listed.

**Comment by wbnns** [comment]
@crwatkins @stequald

Hello, I opened #2851 to remove the wallet, since it appears the support link also no longer works in the App Store, in addition to the link to the website no longer being available:

![image](https://user-images.githubusercontent.com/1130872/52575787-b9085500-2e16-11e9-86ed-83a736436fe0.png)
