### ISSUE TITLE
Update wallet scoring to include fee information when wallet facilitates BTC transactions

### ISSUE THREAD

**Issue by maxwellmons** [bitcoin-dot-org/bitcoin.org#2858]
A new bitcoin user was upset and complaining on r/bitcoin recently, saying he didn't want to use bitcoin ever again shortly after getting started with it. He felt scammed. He said he found the BTC.com wallet through bitcoin.org, which had an in-app option to help him buy bitcoin. He bought around $100 USD worth using it and was mad because he was charged a 10% fee.

The homepage of bitcoin.org has a big button that instructs people to choose a wallet. This is really bad if people are discovering wallets through bitcoin.org and are then using a wallet that hits them with hefty fees when getting some of their first bitcoin. Since bitcoin.org is a very popular site about bitcoin, this is probably not the first time this has happened to somebody.

There should be a score for each wallet related to if it facilitates the buying and selling of bitcoin, along with a colored dot rating on the fee. The colored dot could be gray if the wallet doesn't help a user purchase or sell bitcoin, it could be green if it does and collects a minimal fee, or orange if it does and charges a higher fee.

**Comment by Cobra-Bitcoin** [comment]
Agreed this is an issue, and we need to completely revamp how we arrange the wallets. We're lumping all the wallets together even though they have very different niches they target. Some are good for LN, some for privacy, some for multi-sig payments, some are full nodes, etc. It's just a big mess and obviously a new user is going to get confused. Imagine they're completely new to Bitcoin and their first wallet they pick is Wasabi? They'll have no idea what they're doing.

We need something that clearly shows the advantages and disadvantages of each wallet. We were actually planning a redesign phase two just focused on improving the wallets page, this really needs to be revisited IMO.

**Comment by crwatkins** [comment]
On this particular issue, wallets don't set exchange fees, exchanges set exchange fees.  

Wallets sometimes reference exchanges.  If we are going to pass judgement on exchange fees, we need to rate our exchanges first and then directly or indirectly reference those ratings in wallets that reference the exchanges (some more than one).

(By the way, rating exchange fees will be a huge task for anyone brave enough to take it on.  First, we will need an algorithm to rate fees based on the funds amount, the per transaction fee, perhaps the even the Bitcoin transaction size and current network fees/mempool size.  Then we will need to determine what is "good" or "bad" or maybe even just what is "high" or "low".  Then the information will need to be gathered and applied to exchange listings.  I assume the only way to really do this is to attempt a number of varying size transactions on each exchange.  Since I suspect fees change regularly, I assume this would have to be repeated regularly.  Even maintaining this just for exchanges that wallets reference directly will be daunting and likely constantly inaccurate.)

This would certainly be nice, but I believe totally impractical to actually implement.

**Comment by wbnns** [comment]
I just updated #2347 . Let's meet soon to get in sync and agreement so we can distill something, and also to see if there's any other feedback people would like to add.

**Comment by 3ggerman29** [comment]
my btc wallet address  1Hk3mhTPRvsv5RCbMWZqMWJmt5Tk8NxQFF

**Comment by crwatkins** [comment]
This issue has been inactive for over a year in which time we've implemented a totally new interface.   I recommend that any fee ratings be implemented for exchanges because wallets don't actually charge exchange fees, exchanges charge exchange fees.  New issues on this topic are welcome, but I'll close this one for now.
