### ISSUE TITLE
Reconsider Green Address Wallet Listing for iOS

### ISSUE THREAD

**Issue by maxwellmons** [bitcoin-dot-org/bitcoin.org#2891]
75% of the most recent reviews are negative in the App Store and the last update that was released was on April 29, 2017, which is almost two years ago. It doesn't appear to be actively maintained.

**Comment by crwatkins** [comment]
I've used it in the last couple months and it seemed to function the same as ever, but let's find out from the source.   @greenaddress How is your new native iOS version coming?  Is it still being worked on?

@maxwellmons Which country's app store are you looking at?  How many reviews or ratings are there?

**Comment by greenaddress** [comment]
@crwatkins sorry for the delay didn't notice the ping

we are updating to a native app today, will soon submit a PR to update the listing (mostly rebranding, functionality is unchanged other than new native UX)

**Comment by crwatkins** [comment]
@greenaddress Thanks!  Looking forward to it.

**Comment by jonatack** [comment]
Release announcement. https://blockstream.com/2019/03/19/the-all-new-blockstream-green-wallet/

**Comment by crwatkins** [comment]
The above [announcement](https://blockstream.com/2019/03/19/the-all-new-blockstream-green-wallet/) claims that GreenAddress is going to be gradually retired.  Since I believe GreenAddress continues to meet our listing criteria at this time, I recommend this issue be closed.

@maxwellmons I'm still interested in knowing which country's app store you are referring to.

**Comment by greenaddress** [comment]
Hi @crwatkins - more than retire we are updating the apps + rebranding.

https://github.com/bitcoin-dot-org/bitcoin.org/pull/2901 raised to update bitcoin.org accordingly
