### ISSUE TITLE
[RFC] Potential Paxful Sponsorship Opportunity in 2019

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#2914]
[Paxful](https://paxful.com/), a peer-to-peer exchange that sponsored the site last year, has reached out and expressed interest in sponsoring the site again this year. The previous sponsorship included a clearly marked sponsored link on the “Buy Bitcoin” page, noting that Paxful, a bitcoin.org sponsor (with a link to a blog post with more information), offers a convenient bitcoin marketplace (along with a note that it is sponsored content):

![image](https://user-images.githubusercontent.com/1130872/55622663-12796a00-575e-11e9-93c3-6d2f282694f9.png)

This issue is an opportunity to share feedback/comments. Opportunities like this help support bitcoin.org by covering hosting, legal and other administration-related expenses. They also help bitcoin.org remain financially independent and competitive against other websites, with much more resources and funding, that use Bitcoin’s popularity to capture traffic and drive unknowing users into similarly named altcoins or Bitcoin-related for-profit products wrapped with bias content.

Opportunities like this also help catalyze on-going initiatives such as improving developer documentation and potentially hiring someone part-time to work on it (e.g. version-based documentation, in addition to making it available in other languages this year), financial compensation to contributors for time spent reviewing wallets that are submitted for inclusion on the site, a potential new "What is Bitcoin?" video for the home page, additional design and usability improvements to wallet-selection pages, more translations of the site into other languages to help more people around the world learn more about Bitcoin (including updating existing ones for new content), and in general, continued improvements to the site and the addition of new and updated content as the technology spreads and grows.

Feedback/comments welcome.

Cc: @Cobra-Bitcoin, @theymos, @raypaxful, @skyzer, @scottlledeuce

**Comment by crwatkins** [comment]
As I've explained [before](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2485#issuecomment-401558470), I'm not opposed to sponsorship, however I believe that our previous layout was not just sponsorship, but rather promotion, as Paxful was displayed in front of our neutral listings. Our mission statement includes:

* Remain a neutral informative resource about Bitcoin.

Which I believe is undermined by the elevation and promotion of a single entity, at the expense of others. I believe that we should strongly display our sponsorships for reasons of both transparency and appreciation, but I don't believe we should be promoting based on sponsorship. Our previous positioning looks a bit too much like the pay-to-play situation that other less neutral sites employ. I would think that sponsors should be listed in a sponsors area, and of course be listed with their peers, but also specifically called out there as a sponsor.

**Comment by Cobra-Bitcoin** [comment]
I'm predicting that we'll incur some significant expenses this year with the new video and phase two of the re-design, so I would support another sponsorship for a period so we can have enough funds to comfortably pay for all this and still have a nice amount remaining for emergencies. The documentation especially is something we'll need to improve, but we can start on that once the wallet pages are finished being re-designed.

Regarding the documentation, I'm starting to think that rather than update it or re-structure it, we should completely start from scratch using Andreas' book as an inspiration. One thing I don't like about the existing documentation is how it doesn't gently ease the reader into the technical details. I noticed it more when I was working to split things up and trying to read things as how a newbie would, and it didn't read right. For example, go here: https://bitcoin.org/en/developer-guide, and start reading through the blockchain guide. The first few paragraphs bombard you with information like mentioning merkle trees, inputs/outputs, satoshis, UTXO, etc.

One idea I have in mind is to construct some sort of skeleton for an ideal guide, like sort of have the structure defined with the chapters and pages, and some rough idea of what we want each section to explain and how long it should be in words. Let's say we want to explain what the UXTO set is, we would have an empty section, describe what we want it to contain, and then have a bounty for someone to write out. Who wouldn't want to get paid a couple hundred dollars to thoroughly explain some key aspect of Bitcoin? People would slowly fill out the skeleton with quality content. Additionally we have bounties for people to translate each specific part too.

With the translations there's already been a really good effort to reward and encourage more translations and new languages. We can thank the old sponsorship for that, but our problem is translating new content quickly so that the English version of the site doesn't get too far ahead of other languages. Otherwise it'll feel like we have two different sites with different levels of content. I think more incentives to contribute would help with that too.

Those who opposed the previous sponsorship strongly and claimed to represent the will of the "community" went on to fork the site, and aside from some [initial](https://www.reddit.com/r/Bitcoin/comments/94kole/announcing_btcinformationorg_a_community/) buzz and [popularity](https://twitter.com/hrdng/status/1025791234781196288), barely anyone in the community has contributed to it, barely anyone even links to it, and the overall project seems dead confirming my suspicion that the actual Bitcoin community wasn't as angry or bothered by the original sponsorship as was implied.

@crwatkins I think in hindsight the word "sponsorship" doesn't do a good job explaining the relationship. I agree it's closer to an advertisement or promotion, but IMO that doesn't conflict with our mission statement goal of being a neutral source of information. The sponsored content is clearly marked and Paxful has no ability to compel us to alter other parts of the site in their favour at will discreetly, so we aren't beholden to them.

**Comment by opticbit** [comment]
Bitcoin an paxful have done a lot for each other, and me.  Hope to see the relationship continue.

**Comment by raypaxful** [comment]
My co-founder, Artur and I made a promise to each other that if we ever made it, we would never forget what got us there and that we would always find a way to give back.

Artur and I met at our very first Bitcoin meetup in New York—BitDevs held at the Bitcoin Center. He was fresh off the plane from Estonia and I was fresh off startup failure number 10. Aside from being the only two tall guys at the meetup, we both deeply believed in the mission of bitcoin—to help the little guy. Eventually, we built a POS for retail merchants to accept crypto with the hopes that it would add to the ecosystem. The vibe was so positive that we knew we were a part of the most important movement of our generation, so we toughed it out even when it came down to sleeping on people’s couches.

After 18 months, we had to accept the fact that our product was trying to solve a problem that didn’t exist and we both lost our homes around the same time. It was failure number eleven for me but I didn't have time to feel bad for myself, as we had overstayed our coach reservations and the streets of New York were cold. Two homeless guys driven by a need to fix things for others now had to fix things for ourselves. One day, a friend informed us that we could make a guaranteed profit on the arbitrage of selling bitcoin for a certain gift card. Despite it sounding like a scam, we gave it a shot out of sheer desperation. And guess what? It worked. Paxful was officially born.

When that frantic call came in from a woman down to her last $13, driven mad by her search for bitcoin, I stayed on the phone with her for two hours. I helped guide her to her very first bitcoin purchase, all without a bank account in sight. Being able to offer someone an opportunity they may never have had otherwise really struck a chord with me. It planted a seed in my mind and that seed grew to become the vision of peer-to-peer finance that makes up the core of what Paxful is today. Soon after, an army of people followed and we helped each and every one of them. Aiding the unbanked, technologically challenged, mainstream customers purchase their first bitcoin, we earned our stripes. It’s a time we really cherish and we’ll never forget the people who were with us along the way.

Recently, we finished building our second school in Africa. But it’s more than just a school; it’s five wells, water filtration, water storage, solar power, healthcare of the children, salaries for the teachers, and we’re even planning to add a clinic and a sports field for more than 1,000 children. The #BuiltWithBitcoin initiative is our passion. The plan is to build 100 schools around the world with a focus on financial education and gifted children. We've launched our first scholarship program for female refugees and will soon begin a tour of all the schools and universities in Africa. Artur and I didn't want to wait until the company became a giant before we began our charitable efforts. If we were going to be true to our promise, we needed to give back from the start, even if in small ways. What better way than education in emerging markets? Paxful will always be on the lookout for more ways to sponsor education.

That first woman and all the others that followed found Paxful because we were on Bitcoin.org. Back then, it was the leading and only trusted educational resource for Bitcoin. We were so thankful for the opportunity. Our platform would not be here today if it wasn't for Bitcoin.org taking a chance and listing this the new and relatively unknown Paxful.com. Will and Cobra really helped put us on the map and that, in turn, helped so many others who were desperately looking for bitcoin. No other resource has done more for Bitcoin than Bitcoin.org (my personal opinion) . When we were given the opportunity to sponsor them, our team was thrilled. It was finally our chance to give back to these guys who got us here. For us, it was also a natural extension of #BuiltWithBitcoin and our focus on education. It felt great!

When our sponsorship was announced on Github some people were opposed to the idea. Many had questions and a small minority was quite vocal about their opposition. Will and Cobra, always responsive to the needs of the community made every effort to find an optimal solution centered around P2P, open source and permissionless finance. When they saw no solution they had to withdraw our sponsorship after three months. We were heartbroken. This was never about profit. The $20,000 USD from the sponsorship helped pay for developers, artists, and translators, extending Bitcoin.org to the parts of the world that needed it most. So much more could be done and had to be done.

https://imgur.com/a/kooJb3E

Traffic for Bitcoin.com had already surpassed Bitcoin.org a long while ago and they received massive funding from Bitcoin Cash supporters. So superior was Bitcoin.com's reach that people thought Bitcoin and Bitcoin Cash were the same thing. Millions of user funds were lost as newbies sent Bitcoin Bash to Bitcoin addresses. Artur and I stayed up for hours every night digging up Bitcoin Cash from Paxful BitGo Bitcoin addresses. We did this as a service to the community but it got so bad that we couldn't keep up. Something had to be done to fix the root issue—newbies were being misdirected and lied to. Bitcoin.org had served as a guardian of the community and a standard of trust for so long; then suddenly a competitor, spreading misinformation, smothered its reach. No one did anything to stop this or even noticed, it seemed. Then when we tried to help them with funding, there was an onslaught of resistance.

> (Following the partnership with Bitcoin.org last year, they were able to put more funds into improving content and translations and, as a result, have closed the traffic gap with Bitcoin.com.)

To this day, Bitcoin.com continues to have a larger web presence than Bitcoin.org; and because of this fact, they have no issues monetizing the site will continue to leech off the Bitcoin brand and stifle the efforts of Bitcoin.org and their efforts to provide relevant information to those seeking to learn more about Bitcoin.

Why should Bitcoin Cash's media be strongly funded but Bitcoin not be allowed to receive support?

Why should innocent new Bitcoin users lose their money because of deliberate and well-funded misinformation?

Why this war against commerce?

Paxful is 100% pro-Bitcoin. Our wallet supports only bitcoin, no forks! Our Marketplace uses bitcoin as the universal pair for all forms of money. When we gave people their BCH from the fork, we gave it to them as bitcoin, plus 30 percent more. Paxful is 100 percent bootstrapped and thankfully so, because if we had investors, they would not approve of the Bitcoin.org sponsorship because they would see it as a poor investment, profit-wise. But we believe in Bitcoin.org and the people behind it. They have been steady stewards of the ecosystem and deserve all of our support. We are so proud to have "Sponsored by Paxful" on a page over at Bitcoin.org and happy to know it’s helping them extend their reach to fight for Bitcoin. There aren’t many things that make us feel as good as this. We have come full circle and are giving back to those who helped us get here.

The sponsorship is back on. Bitcoin.org deserves the support of the whole community and if people refuse to support them sufficiently enough to counteract the damage caused by all these forks, then we here at Paxful will and we won't be asking for permission from anyone. That’s the essence of what decentralized P2P money is. Will, Cobra, Artur, and I all believe in #P2PFinance and what it can do for the world. We will make every effort to see that people everywhere have a universal clearing layer to use the value of their work without borders and without having to ask anyone for permission. A safe and open financial system is the birthright of every single human and we will see that they get it, no matter what the cost.

-Ray Youssef
CEO Co-Founder Paxful. #p2pfinance

**Comment by kareninsf** [comment]
Paxful has done a ton to help with bitcoin adoption globally, and has given opportunities to many around the globe who didn't have any- I would LOVE to see this happen.

**Comment by beyourseff** [comment]
Paxful has been a strong supporter of BTC, and the last sponsorship went relatively well. Ack

**Comment by Gwolfterritory** [comment]
Paxful and BTC changed my life. If it wasn't for this wonderful site I wouldn't be able to make ends meet. Because what paxful and the trading community has done I been able to provide for my family.

**Comment by muhammednagy** [comment]
Paxful has helped and is helping bitcoin expand in different parts of the world where bitcoin use cases are very much needed.
I'd love to see the sponsorship happen.

**Comment by theymos** [comment]
Some people were upset by the previous sponsorship, so let's go slow here and make sure that all concerns are addressed.

Paxful is a good fit, but although I don't completely hate the screenshotted sponsorship, IMO it's a little too prominent. I feel like someone just casually glancing at the page will completely miss the three boxes on the bottom and think, "Oh, this is just a useless sponsorship page." I'd like it more if Paxful was listed on that page as a brighter fourth box along with the others, or if it was omitted on that page and instead just shown prominently on the exchanges list.

**Comment by scottlledeuce** [comment]
Ack : because we need to keep bitcoin peer to peer and it seems paxful are actually interested in developing their product and working with the people on the 

A

**Comment by texcoinz** [comment]
Paxful and Bitcoin have been a huge, positive aspect of my life and the people i deal with everydays life!

**Comment by raypaxful** [comment]
> Some people were upset by the previous sponsorship, so let's go slow here and make sure that all concerns are addressed.
> 
> Paxful is a good fit, but although I don't completely hate the screenshotted sponsorship, IMO it's a little too prominent. I feel like someone just casually glancing at the page will completely miss the three boxes on the bottom and think, "Oh, this is just a useless sponsorship page." I'd like it more if Paxful was listed on that page as a brighter fourth box along with the others, or if it was omitted on that page and instead just shown prominently on the exchanges list.

This is a great suggestion and should be user tested. 

We are producing a neutral series of p2pfinance videos and that is another thing that could be featured to really drive mainstream adoption based on real use cases.

**Comment by crwatkins** [comment]
@raypaxful Thanks for taking so much interest in bitcoin.org!

> That first woman and all the others that followed found Paxful because we were on Bitcoin.org. Back then, it was the leading and only trusted educational resource for Bitcoin. We were so thankful for the opportunity. Our platform would not be here today if it wasn't for Bitcoin.org taking a chance and listing this the new and relatively unknown Paxful.com. Will and Cobra really helped put us on the map and that, in turn, helped so many others who were desperately looking for bitcoin. 

Could you explain when this was that you were previously listed on bitcoin.org?  I thought your first listing was last year during the sponsorship.  Maybe you were listed as some other entity?  This is probably not important other than to reduce my confusion.

**Comment by achow101** [comment]
From the previous time this was discussed, I think that the additional suggestions that @crwatkins and @harding made in that thread should still be implemented. The screenshot of the proposed page is still the same as the last time the sponsorship occurred and I think it could be improved to make it more neutral and less like an advertisement.

**Comment by wbnns** [comment]
Hello, thanks to all who have shared feedback on this, and thanks also to Paxful for stepping up to want to support the site and discuss the opportunity with everyone together here on GitHub.

Following a review of the thread with @Cobra-Bitcoin, we think the optimal route would be to not pursue this opportunity at this point in time.

Closing this issue, and we'll reopen should further discussions arise in conjunction with Paxful potentially sponsoring the site in some way in the future, so we can all discuss.
