### ISSUE TITLE
Add Quebex.com Canadian Bitcoin Exchange

### ISSUE THREAD

**Issue by davidquebex** [bitcoin-dot-org/bitcoin.org#2960]
Hi, can you add Quebex.com Canadian Bitcoin Exchange?

Founded in 2016 in Montreal, Quebec, Canada, there has been 6,600+ trades initiated and over $1,193,000 CAD traded on the platform to date. 

Quebex is a federally registered MSB with FINTRAC Registration #M17947675 and licensed with AMF #903510.

We offer email support, live chat and phone support at (888) 661-3358.

Accepted payment methods include: Email Money Transfers, Bank Deposits and PayPal.

**Comment by wbnns** [comment]
@davidquebex 

Hello, thank you for the information. When reviewing the exchange we encountered the following issues:

+ The quick link navigation dropdown in the footer on mobile / handheld devices appears to be broken (nothing happens when it is touched): 
  <img width="347" alt="image" src="https://user-images.githubusercontent.com/1130872/57403380-1bc87d00-71c9-11e9-8cd4-388ecf9c02a6.png">

+ A popup showing the number of trades that have happened today seems to reappear on every page we navigate to on the platform, no matter how many times we close it:
  <img width="376" alt="image" src="https://user-images.githubusercontent.com/1130872/57403962-61397a00-71ca-11e9-9e7d-acb1b9b8b8d1.png">

+ On the address verification page, the dropdown to select a Province appears to be broken (nothing happens when it is touched):
  <img width="368" alt="image" src="https://user-images.githubusercontent.com/1130872/57404179-e1f87600-71ca-11e9-9de4-297b951ea477.png">

+ After submitting KYC for a test account, we encountered the following screen, instructing us to "initiate a chat":
  <img width="374" alt="image" src="https://user-images.githubusercontent.com/1130872/57404423-7662d880-71cb-11e9-8b21-4089d6cb8f37.png">

+ Navigating through the link resulting in a blank page that said "Null" - we were not able to initiate a chat or leave a message as instructed.

Please let us know when these issues are resolved and we will resume the review.

**Comment by davidquebex** [comment]
Hi Aaron,

Please meet Will Binns from bitcoin.org.

He reviewed Quebex but noticed the issues bellow.

Please advise.

Thanks!

David

**Comment by davidquebex** [comment]
Hi Will,

I’ve added code to suppress the popup for 7 days once closed, stored in the session cookie.

I’ve also fixed the styling issue for the select element dropdown arrow that appears in responsive view in Firefox. On mobile devices, there would have been an issue where the right most 10% of the black section would not have been clickable which I have now resolved.

I’ve installed Firefox on my iPhone and tested the quick links select element, and it now works fine. I’ve also tested it on a Samsung tablet which worked as expected; unfortunately I don’t have an android phone handy at the moment to test with.

When I tested on Firefox 60 running on windows 10 I noticed that there were a few quirks I can’t reproduce on mobile devices.

Can I ask what device you’re testing on? Your user agent suggests it’s a windows 7 device; are you using a PC or mobile device?

I have been unable to reproduce the issue you had with the province select element on any device; I wonder if it would perhaps be a Firefox responsive mode issue? It’s a regular select element with nothing special happening.

The href for the initiate chat link has been replaced with “javascript:void(0)” which works well with Firefox, so you should now be able to click it to trigger popping up the chat window. As for receiving the prompt after completing the KYC, that is expected behaviour when a user fails the Equifax KYC or when any of our fraud mitigation strategies flag an account for manual review. 

We have thousands of users who have successfully passed the Equifax KYC and thousands more who were approved without doing one who would not have been prompted to initiate a chat with staff. As we cater to the Canadian market, we admit that it is exceptionally hard for non-Canadians to successfully sign up with Quebex.

Please continue your review, and let me know if you spot any other ways we can improve our user experience.

Thanks,

- Aaron

**Comment by wbnns** [comment]
@davidquebex 

Thank you for the update. We were testing on a PC running MacOS with Chrome, Mozilla and Safari-based browsers.

We have created another test account and noticed additional issues.

---

+ At the top of the page is a banner providing an instruction to "Click here to verify":
 
 ![image](https://user-images.githubusercontent.com/1130872/57539852-e8a5fb00-733a-11e9-8b24-422eb5feeb01.png)

+ Clicking the button leads to a dead-end page informing us that there is "No Equifax Verification Scheduled". This would potentially be confusing to users who are following the instruction to navigate to the page to get verified:

  ![image](https://user-images.githubusercontent.com/1130872/57539894-02dfd900-733b-11e9-9091-a4e684bb1678.png)

+ Upon creation of a new account the center content area for Wallets is empty:
  
![image](https://user-images.githubusercontent.com/1130872/57539760-b5fc0280-733a-11e9-91b7-4090a04a23b4.png)

---

We appreciate you all spending the time to try to resolve and correspond about the issues, however, due to the numerous issues encountered during the course of the review, we wouldn't be able to recommend the exchange for listing at this time.

If other regular contributors disagree, we can reconsider the decision.

**Comment by davidquebex** [comment]
Hi Will,

Thank you very much for your help.

The reason why you don’t have access is because you are hiding behind a burner phone and proxy like most fraudsters do.

Unlike localbitcoin were Interac e transfer fraud is a huge issue, Quebex has very strict policy to discourage fraud and protect its users so I think it’s a very valuable service to the community.

I strongly suggest you signup and test the system without trying to hide as this will result in restricted access.

Is there any reason why you are using burner phone numbers and hiding behind a proxy?

Let me know.

Cheer!

David

**Comment by davidquebex** [comment]
Hi Aaron,

Can you please assist Will with the following issues?

Thanks!

David

**Comment by achow101** [comment]
Given the repeated failure of Quebex to meet the exchange listing requirements, and given the behavior of @davidquebex, I believe that Quebex should not be listed and furthermore that @davidquebex be blocked from opening issues in this repository.

There have been 5 issues opened related to adding Quebex as an exchange, and in those not marked as duplicates (although all of them should be and all discussion should be kept to one issue), Quebex has repeatedly failed to meet the exchange listing requirements.

Furthermore, in the past day, @davidquebex has opened an additional 7 issues. Of these 7 issues, two are effectively advertisements which are completely unrelated to bitcoin.org. The other 5 are attempts to remove other exchanges from the site. Given that @davidquebex is an exchange operator, there is a significant conflict of interest with those issues, and as such, I believe that they should be ignored. This behavior is extremely anti-competitive and break's bitcoin.org's neutrality.

Considering the above, I believe that @davidquebex is in violation of bitcoin.org's code of conduct and should therefore be blocked from opening any issues.

**Comment by davidquebex** [comment]
Hi Andrew,

Thank you for your comment.

Can you please clarify what requirement have more been meet.

We informed Will that Quebex blocks fake accounts to avoid scammers and fraudsters.

Quebex only allows real accounts to protect its users. Will 3 accounts were flagged as possible fraud due to use of burner phone number and IP hiding services.

As proof you can signup with a real account and you will see that there are no issues.

There is too much P2P fraud and we really need to keep traders safe.

Is there any particular reason why tests are performed using fake accounts?

Let’s make bitcoin trading safe!

Cheers!

David

**Comment by achow101** [comment]
> Is there any particular reason why tests are performed using fake accounts?

The use of "fake" accounts does multiple things.

Firstly, it simulates what may happen to a new, naive user trying to use the service. It should not matter whether an account is "fake". What matters is that regardless of how your system flags an account, that there are clear instructions for how users can prove that their account is real (for the event of a false positive) and that in general, regardless of how an account is flagged, users don't run into a dead end that confusingly renders their account unusable. Really the difference between how a "fake" or "real" account should be treated is the amount of verification that needs to be done. It should not be confusing to users as to what they should be doing to make their account usable, and that is one of the things being tested for in these reviews.

Secondly, a "fake" account protects the reviewer. Prior to reviewing a service, the reviewer does not know whether the service is secure or trustworthy. By using so called "fake" accounts, the reviewer can be protected against unknown harms that may come from the service.

**Comment by davidquebex** [comment]
Hi Andres,

Thank you for your feedback!

We have approved the fake accounts created by Will so he can continue review but never used the approved accounts.

Why was the approved account not used?

I don’t think censorship (by blocking my comments) is what bitcoin is about.

Censorship is the worst thing that can happen to the internet and I don’t think it’s what bitcoin.org is about.

There is a lot of fraud on localbitcoins and paxful. Honest bitcoin sellers are being scammed on these platforms.

There are thousands of complaints on reddit and bitcointalk.

Why would you recommend these exchanges to new bitcoin adopters?

They should be removed from bitcoin.org until they fix these serious issues!

Are you related with Localbitcoins and Paxful?

Let’s make bitcoin trading safe!

Cheers!

**Comment by achow101** [comment]
> Why was the approved account not used?

Why should Will get special treatment because he's a reviewer? What recourse does a completely new user have if they end up in the exact same situation? The point of review is to pretend to be (or actually be) a new user to evaluate the service. If the reviewer gets special treatment, then that completely invalidates the review.

> I don’t think censorship (by blocking my comments) is what bitcoin is about.
> Censorship is the worst thing that can happen to the internet and I don’t think it’s what bitcoin.org is about.

There is a difference between censorship and moderation. Your behavior is a violation of the code of conduct, IMO. To block your comments would be moderation. I would be fine with some of your comments if you had not a) created multiple issues to promote your own service, b) created multiple issues asking to delist other services soon after creating issues promoting your own service. This, to me, seems highly anti-competitive and suspicious. If instead of spamming new issues you had created a single issue asking that the exchange listings be re-reviewed because you noticed a large number of complaints on other websites, that would be fine. However the way that you went about doing that is unprofessional IMO.

Furthermore, there is a conflict of interest as you are an exchange operator. An exchange operator asking a site that lists exchanges to delist sites that are clearly competitors to their own service is highly suspicious and anti-competitive.

**Comment by davidquebex** [comment]
Hi Andrew,

Thanks for your reply.

There is no conflict.

If you don’t want to add Quebex we respect your decision, there are many other reputable sites to choose from on bitcoin.org.

We’ve researched Kraken, Coinbase, Gemeni and these are regulated and reputable exchanges that must be kept.

I think that until Localbitcoins and Paxful fix the fraud issues they should be removed from bitcoin.org.

If you don’t want to remove them you should at least educate users about these scams when linking to these sites. The warnings should be clear.

I agree that usability is very important to maintain a happy user experience. And we should work together to achieve that goal in the best interest of the bitcoin community.

But most importantly, I think that user safety should be number one priority when recommending exchanges on bitcoin.org.

Why would you recommend these exchanges when having knowledge of all these scams and frauds?

Cheers!

**Comment by achow101** [comment]
> Why would you recommend these exchanges when having knowledge of all these scams and frauds?

I have no say in whether they continue to be listed nor have I claimed that they should still be recommended. I have no knowledge of any scams and frauds occurring on those services as I have not done any research into whether there are any.

My only complain is about your behavior, nothing else.

**Comment by davidquebex** [comment]
Please see fraud complaints about local bitcoins and paxful here:

https://github.com/bitcoin-dot-org/bitcoin.org/issues/2970

https://github.com/bitcoin-dot-org/bitcoin.org/issues/2971

This is just the tip of the iceberg !
