### ISSUE TITLE
Add Panama to the list of countries and exchanges.

### ISSUE THREAD

**Issue by jorgefar** [bitcoin-dot-org/bitcoin.org#3014]
Hello, we very respectfully request to add Panama to the list of countries and to Cryptobuyer.io in the South American exchanges section https://bitcoin.org/en/exchanges#south-america, thanks!

**Comment by wbnns** [comment]
@jorgefar 

Hello, when reviewing the exchange we noted that it doesn't appear that people in Panama would be able to use this website to buy bitcoin:

![image](https://user-images.githubusercontent.com/1130872/64388140-b927a680-d02d-11e9-8238-d51213eba970.png)

It's helpful that people can learn about the ATM locations, however, all other exchanges on the Exchanges page allow people to purchase and sell bitcoin via their respective websites.

While it seems that it may be possible to sell bitcoin using this website, the spot price is significantly lower that the market average. For example, at the time of review, the average bitcoin price across exchanges was 10,563.84 USD. The spot price on Cryptobuyer was 9,522.96 PAB. Since PAB is pegged to USD (1:1), people who were to use the exchange to sell their bitcoin would be doing so for almost 11% less than the average market price (-10.93%).

Lastly, when logging in, we noted that 2FA is enforced on the account with authentication being required via a validation code received via email. The email, however, goes directly to spam. We confirmed this happens each time we log in:

![image](https://user-images.githubusercontent.com/1130872/64388761-9c8c6e00-d02f-11e9-92d2-c7ec8aead363.png)

We investigated this and it seems the issue may be because the email server you all reside on at Sendgrid has a blacklisted IP:

![image](https://user-images.githubusercontent.com/1130872/64389459-466cfa00-d032-11e9-8889-0e164de3c6aa.png)

As a result, any emails that are sent from the platform via Sendgrid will most likely go to spam, thus making it difficult for recipients to differentiate between authentic emails from Cryptobuyer, and those that are not, such as phishing emails - both would appear in the same place.

Based on these issues mentioned above, we wouldn't be able to make the addition to the Exchanges page at this time.
