### ISSUE TITLE
Dropping GreenAddress Desktop from Wallet pages

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3023]
We should consider dropping GreenAddress Desktop from our wallet pages.

Reasons:

+ The [project/code repository](https://github.com/greenaddress/WalletElectron) appears to no longer be maintained - the last commit was 8 months ago and [the build status has been failing since then](https://travis-ci.org/greenaddress/WalletElectron).
+ The only open issue on the repository, [reported by a user 4 months ago](https://github.com/greenaddress/WalletElectron/issues/15), hasn't received a reply/acknowledgment from maintainer(s).
+ Android and iOS versions of the wallet have already been deprecated.

Based on the above, not sure this is solid desktop option anymore, to be displayed to the large amount of visitors that the site receives.

**Comment by crwatkins** [comment]
As I [mentioned](https://github.com/bitcoin-dot-org/bitcoin.org/pull/2916#issuecomment-480544705) in April, I don't see any reason to remove GreenAddress desktop at this time.
* As far as I know it continues to meet our criteria
* It is a very functional wallet (I used it myself quite recently)
* It is fully compatible (same accounts can be used) with the new Blockstream Green Wallet 
* Blockstream's open PR #2901 continues to list it
* I would personally characterize the desktop option as "solid"

However, that said, often when we talk about delisting wallets, we discuss what might happen to the wallets in the future with the best intent of protecting new users from investing their valuable time in learning a wallet that might be "going away" in some manner in the near future.  Perhaps in a separate issue we should consider a new criterion that there's no indication that support for the wallet will be dropped in some specified near future time frame.

All of that said, however, Blockstream does not seem to be promoting (or listing) this wallet in any way.  @greenaddress Would you like it removed or remain listed?

**Comment by Cobra-Bitcoin** [comment]
I think it should be removed given that it's not even being promoted by the company behind it. Listing wallets that aren't maintained anymore doesn't do our users and the wider ecosystem much good since often these wallets are behind on implementing new features and protocol optimisations. Makes no sense IMO to point users to what are essentially dead projects.

Also keep in mind that users using this wallet share control of their money with Blockstream as funds are secured in a 2 of 2 multi-sig, one key controlled by the user and the other by Blockstream. To me this makes it even more wise to remove the wallet, it's bad enough the wallet is unmaintained but the additional risks associated with users not have full sovereignty over their funds and the company behind it seemingly having no interest to promote/maintain the wallet are concerning.

**Comment by maxwellmons** [comment]
Wallets that aren't actively maintained shouldn't be on the website.

**Comment by crwatkins** [comment]
@Cobra-Bitcoin 

> I think it should be removed given that it's not even being promoted by the company behind it. 

Please keep in mind that I agree with this above assuming we don't hear from them otherwise,
and that my notes below are just notes and not meant as a counterargument.  

> Listing wallets that aren't maintained anymore doesn't do our users and the wider ecosystem much good since often these wallets are behind on implementing new features and protocol optimisations. 

Agreed, but it is interesting to note that with segwit, bech32, and RBF support, even though there hasn't been a recent new release, it is still one of the more advanced wallets listed.

> Makes no sense IMO to point users to what are essentially dead projects.

> Also keep in mind that users using this wallet share control of their money with Blockstream as funds are secured in a 2 of 2 multi-sig, one key controlled by the user and the other by Blockstream. To me this makes it even more wise to remove the wallet, it's bad enough the wallet is unmaintained but the additional risks associated with users not have full sovereignty over their funds and the company behind it seemingly having no interest to promote/maintain the wallet are concerning.

Likewise, I get that this makes recovery much more difficult than a single-signer transaction, however there are some potential recovery options (including nLockTime) that have been tested during reviews, and the infrastructure used by the legacy desktop wallet is the same as that which supports the newer supported wallets.

**Comment by greenaddress** [comment]
The wallet is still active and maintained/QA'ed and still promoted on greenaddress.it both on the home page as well as when you click on create new wallet - it hasn't been rebranded yet if that was in doubt.

**Comment by crwatkins** [comment]
@greenaddress My mistake.  When I looked at greenaddress.it I missed the desktop download icons (they were somewhat dwarfed by the app store download buttons; you might want to make it more obvious that those are download icons).

Thus, I believe that there is no reason to remove this listing for my above reasons.

**Comment by greenaddress** [comment]
@crwatkins good point, thanks, will look into it

**Comment by crwatkins** [comment]
I recommend closing this issue.

**Comment by wbnns** [comment]
@crwatkins Ok.

@greenaddress 

> The wallet is still active and maintained/QA'ed and still promoted on greenaddress.it

If the wallet is still active and maintained/QA'ed, could you please clarify why:

1. The repository hasn't been updated in 8 months
2. The build status has also been in a failing status for 8 months
3. The user reported issue of being unable to bump fees that was opened 4 months ago (the only open issue on the repository), still hasn't been replied to or acknowledged even after we mentioned it here last month

Thank you for joining the thread.

**Comment by wbnns** [comment]
#3066 has been opened to make the removal. We've been unable to make any material observations to lead us to believe that the Desktop wallet is still actively maintained:

1. The [code repository](https://github.com/greenaddress/WalletElectron) hasn't been updated in 9 months, now.
2. The last build on the repository has also been in a [failing status](https://travis-ci.org/greenaddress/WalletElectron/builds/451416164) for 9 months.
3. The only open [issue](https://github.com/greenaddress/WalletElectron/issues/15) on the repository, hasn't been replied to for 6 months.
4. Android and iOS versions of the wallet have already been deprecated by the developer.
5. The developer hasn't replied to this issue in almost 1 month.
6. [2FA issue reported on reddit](https://www.reddit.com/r/Bitcoin/comments/c1hlge/greenwallet_2fa_failedhow_to_restore_from/) a month ago received no reply.

Despite the technical achievement of building what appears to be an advanced wallet, there has been little to no observable, responsive action to the above, even after much of this was brought to attention over a month and a half ago.

**Comment by anonymous73** [comment]
This is really unfortunate.

F-Droid users that are running Kitkat OSes are currently without a trustworthy bitcoin wallet.

Please pull your finger out, GreenAddress, and get to the bottom of the concerns raised. It is near impossible to recommend your app to users when you are not listed on bitcoin.org
