### ISSUE TITLE
Listing BestChange.com on Bitcoin.org

### ISSUE THREAD

**Issue by BestChangeOfficial** [bitcoin-dot-org/bitcoin.org#3160]
Hello!

We are BestChange.com, leading exchangers monitor that helps users find the best e-currency exchange rates. All exchangers in our service are trustworthy and reputable,  and we monitor the quality of the services they provide, i.a. by giving the users an opportunity to leave a review. Currently there are over 250 exchangers in the English version of our monitoring, and have been successfully working since 2007.

Please see the high score we have on these resources:
https://www.mywot.com/en/scorecard/bestchange.com   
https://www.trustpilot.com/review/www.bestchange.com 

We would like our project www.bestchange.com to be listed under “International” section in your list https://bitcoin.org/en/exchanges

And we would also want our Russian language site www.bestchange.ru to be listed under the “Europe” (Russia) section of the above list.
Please advise us how to get listed on your site.

Look forward to hearing from you!

Best regards,
Yulia (BestChange).
support@bestchange.com

Find us on Facebook: https://fb.com/bestchange
Follow us on Twitter https://twitter.com/bestchangeeng

**Comment by wbnns** [comment]
@BestChangeOfficial 

The site as-is does not meet our definition of an exchange, since it doesn't directly facilitate the exchange of bitcoin for fiat (and vice versa) - it is a directory of exchanges. We don't believe the International category, alongside other direct exchanges, would be the ideal location for this.
