### ISSUE TITLE
Remove Bitpay wallet  from the recommended Android wallets section. 

### ISSUE THREAD

**Issue by zndtoshi** [bitcoin-dot-org/bitcoin.org#3171]
During the S2X attack Bitpay company was recommending it's users to upgrade to BTC1 full node implementation which is an altcoin and this would be seen as an attack towards the Bitcoin ecosystem. I urge the maintainers of the Bitcoin org website to remove this wallet from the "recommended android wallets" section. 
https://bitcoin.org/en/choose-your-wallet?step=5&platform=android
edit2: Also remove it from the iOS section and all desktop sections.

**Comment by crwatkins** [comment]
@zndtoshi At the risk of sounding a bit snarky because of my brevity, you are a little late to [this long discussion](https://github.com/bitcoin-dot-org/bitcoin.org/pull/1752) which resulted in the removal over two years ago and subsequently [re-added](https://github.com/bitcoin-dot-org/bitcoin.org/issues/2577) a year later.

If you believe bitcoin.org should have much longer punitive requirements, I recommend proposing specific changes to the listing criteria, most preferably in the form of a PR.

**Comment by zndtoshi** [comment]
Didn't know about this discussion. Thank you for pointing it out.
