### ISSUE TITLE
Clarifying the HSTS requirement for wallets

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/bitcoin.org#3232]
**Related:** #3142, #3111, #3091

Currently, when wallets request to be listed on bitcoin.org, it's a requirement that that their websites serving executable code support HSTS. There are instances where new wallets are not being recommended for listing due to this, yet, there are wallets that are already listed that do not feature this support.

We should clarify whether the requirement is absolute, or if it should be optional, and how this requirement should be applied across all wallets (should already listed wallets be grandfathered/exempt, should already listed wallets have a certain amount of time to meet the requirement, should the requirement be made optional for everyone instead, etc.).

Cc: @crwatkins

**Comment by jdabs** [comment]
> websites serving executable code support HSTS

For my clarification, what does "executable code" mean? Isn't JavaScript executable in the browser? Or do you mean only pages that have .exe or .dmg?

**Comment by crwatkins** [comment]
@jdabs My reviews have relied on a fairly broad definition of "executable code", including machine code images and JavaScript.  I try to verify the path from the download link referenced on the bitcoin.org site through to the code that runs the wallet whether that be a desktop app for download, an app store, or JavaScript which runs in a browser.  I also try to look at the most likely path a user would take from a web search for the wallet to the executable code, if that's a different path from the bitcoin.org link.

**Comment by wbnns** [comment]
@crwatkins 

What do you recommend be the protocol here for wallets that are already on the site?

**Comment by crwatkins** [comment]
First I'll describe the de facto generic delisting process as I see it.  I believe it is exactly the same as for any other changes on the site:  Community members propose changes in PRs or issues.

There can be many reasons to cause community members to propose delisting.   Some common ones in the past have been:

1. General safety/security concerns about the wallet (not necessarily related to a specific listing criteria)
2. Someone that might be somehow associated with the wallet said something bad about Bitcoin
3. Non-compliance with current listing criteria

The first one in the past has prompted fairly quick consensus on whether to merge or not.  There haven't been any of these recently, however issues in this category (serious concern not specifically related to a criterion) regularly come up during wallet reviews, usually involving inadvertent disclosures of keying material.

I clearly wrote the second one a bit snarky to indicate that I personally don't take these too seriously.  This category also includes submissions that speculate on the future directions that developers may take. Many of our criteria require wallets to function transparently in ways that minimize the potential harm to users regardless of future decisions of the developers. I know I'm being a bit naive, but I don't have the resources nor the aptitude to analyze the potential future decisions of all developers, so I rely on minimizing the impact of unknown future decisions.

That leaves the last category of issues that do not seriously nor immediately impact the security of the wallet, and are somehow correctable by the developer.   An example of this might be the failure by the developer to tag releases in the repository.  I think I might also put the HSTS criterion in this category.  Issues with these criteria should be brought to the attention of developers through a repository issue or PR, but I would be willing to allow the wallet to be continue to be listed for a reasonable time while waiting for a response and remediation by the developer.  One reason is that I'm lazy and doing nothing and having the problem corrected is the easiest path.  Another consideration is whatever affect removing and replacing pages might have on SEO.   Also, since our listing is binary (either listed or not) removing a well-established, long-time listing and causing existing users to see that as a signal to move a less well-regarded wallet may not be in the immediate interest of users.

**Comment by jdabs** [comment]
@crwatkins HSTS is a spec of its own. I somewhat take issue with your only relying on the Google lookup to verify that it is enabled. Webmasters don't need to enter their site to the Google preload list, and their site could still be following the spec to the letter. Perhaps, and rightfully so, a developer may not want to bother with satisfying Google's hoops based on principle.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

![Screenshot_2020-03-28-12-30-15-644_com android chrome](https://user-images.githubusercontent.com/6774432/77828351-3e20fd00-70f1-11ea-9834-fbbd43fb6f82.jpg)

**Comment by crwatkins** [comment]
@jdabs 

> I somewhat take issue with your only relying on the Google lookup to verify that it is enabled.

I'm not sure where you got that impression, but I can assure you that any time I review a listing, I use  `curl -I` to verify the required HSTS criterion.  Perhaps you are confusing it with the currently optional HSTS preload suggestion.

**Comment by crwatkins** [comment]
Perhaps some of the answers in this issues should eventually make it into the wallet listing documentation, but for now, I believe this issue has been answered.
