### ISSUE TITLE
Improving SERPs for key phrases (e.g. 'buy bitcoin')

### ISSUE THREAD

**Issue by renepickhardt** [bitcoin-dot-org/Bitcoin.org#3267]
source: https://twitter.com/odedleiba/status/1225733075063255044

I wanted to start the discussion for a longer time actually. I cannot confirm those search results. for me it is (ignoring advertising) in a clean browser coinbase first then bitcoin.org then paxful and then bitcoin.com

in any case I am not sure about the landing page: https://bitcoin.org/en/buy first we could decide to also go to a subdomain buy.bitcoin.org/en/buy-bitcoin.html in order to SEO boost even more but also the 3 sections of the landing page are strange.

I agree that it is great that bitcoin.org is neutral and I am in no means suggesting to change that but maybe we can add a 4th section about warnings of scams and how people should do their own research? also we have control of the meta description that will be depicted. 

So I guess we can still improve somehow.

**Comment by gmaxwell** [comment]
> I cannot confirm those search results. 

For me it is the aforementioned scam site, then cex.io, then coinbase, then bitcoin.org.

**Comment by wbnns** [comment]
@renepickhardt Thanks for raising the issue (@gmaxwell Thank you also for checking).

When using a new private tab w/ no cookies set, we're seeing the following results:

Google:

![image](https://user-images.githubusercontent.com/1130872/74523059-b3a78400-4f1c-11ea-8df6-f852a32e1baa.png)

Bing:

![image](https://user-images.githubusercontent.com/1130872/74523254-0da84980-4f1d-11ea-9c04-3a2d65ad1182.png)

DuckDuckGo:

![image](https://user-images.githubusercontent.com/1130872/74523351-32042600-4f1d-11ea-8b95-6d3b1ea16adb.png)

Yahoo:

![image](https://user-images.githubusercontent.com/1130872/74523452-624bc480-4f1d-11ea-901f-f76bfc94597e.png)

> in any case I am not sure about the landing page: https://bitcoin.org/en/buy first we could decide to also go to a subdomain buy.bitcoin.org/en/buy-bitcoin.html in order to SEO boost even more

Search engines like Google [do not rank sites higher than others just because a key phrase is on a subdomain as opposed to a subpage](https://outline.com/rhxs2e).

That said, while we currently rank high for the phrase "buy bitcoin" as well as many others, unfortunately this is going to diminish over time, and is no doubt also already happening to a degree based on location as noted in the inconsistent results multiple people are seeing.

Search engines are calibrating more weight in results to favor things such as the amount of time people are spending on pages within their rankings, and how often people are returning, combined with freshness of content, etc. alongside their other results. 

Our content does not change very often. Many visitors will come to the page (like this buy bitcoin page, for example), and read it, but less will come back a second time.

This is deficient in comparison, to other sites like those mentioned, that have charts, live pricing, news, editorial pieces, and other interactive features that all mesh around the objective of allowing one to buy bitcoin (which the aforementioned sites also let a user do), check the price of their portfolios, etc.

> SEO boost even more but also the 3 sections of the landing page are strange.
>
>I agree that it is great that bitcoin.org is neutral and I am in no means suggesting to change that but >maybe we can add a 4th section about warnings of scams and how people should do their own >research?

We can continue to add and improve content, but we would need to also consider how we could increase the utility of the page to be more competitive with the sites surpassing it in the search results as described above.

**Comment by Cobra-Bitcoin** [comment]
I'm going to improve the buy bitcoin page over the next few weeks, it'll get more informative, interactive and useful.

**Comment by Cobra-Bitcoin** [comment]
I'm going to go ahead and close this. We rank even better for "buy bitcoin" now in more countries, because users are spending longer on the page, and that's signalling to Google the page is better serving their needs. We're also now [crushing Roger's site in traffic](https://imgur.com/a/e5GAgbd) despite his much bigger resources.

If anyone has any other ideas for improving SERPs for different keywords, please reach out to me through e-mail or Twitter. I'm especially curious about keywords in which we rank worse than Roger's site. I want to minimize as much traffic to his site as possible, because it's horrible UX how he mixes up BTC/BCH into one site, and super confusing. So the more keywords we can dominate, the better.
