### ISSUE TITLE
Listing a new exchange 

### ISSUE THREAD

**Issue by haidersf** [bitcoin-dot-org/bitcoin.org#3310]
Hi, what is  the process for listing a new exchange? Does it need to be a pull request?

**Comment by pablortiz** [comment]
https://en.bitcoin.it/wiki/Currency_exchange

**Comment by wbnns** [comment]
@haidersf 

Hello, closing this issue since we already received your email and connected earlier last week.

* * *

For anyone else that was following along, here's a [link](https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/adding-exchanges.md) to the documentation regarding the addition of exchanges.
