### ISSUE TITLE
Updating translation team members

### ISSUE THREAD

**Issue by wbnns** [bitcoin-dot-org/Bitcoin.org#3348]
The translation team on bitcoin.org has grown sizeably, with a signficant number of people providing regular contributions to help localize the site to ensure visitors across the globe can read it natively by default in their preferred languages.

We need to update the list of translation team members:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/1130872/82146628-f0e91e00-984b-11ea-91f6-ec4665752e25.png">

**Comment by jdabs** [comment]
Good idea to keep the translator list up to date like the code contributor page. Translators have become very active and it's appreciated.

**Comment by Komodorpudel** [comment]
Old idea finally getting started on :)

The Transifex Reporting Tool allows to pull all the data since 2013. Excluding deleted accounts, 763 accounts contributed on Transifex. 

Following a similar approach as used for the bonuses, we could rank each account-language combination (there are some people that translated more than 1 language) and add them to the page, displaying only the top x with an expand function for the others.

If someone wants their real name to be displayed, they could just write us on Transifex.

**Comment by mateusnds** [comment]
Can we have links on our profile?

**Comment by wbnns** [comment]
@mateusnds 

> Can we have links on our profile?

We were thinking we would use the reporting tool to link to people's Transifex profiles, similarly to how you see GitHub contributors with links to their GitHub profiles (it is automatically generated).
