### ISSUE TITLE
Improving the buy page

### ISSUE THREAD

**Issue by Cobra-Bitcoin** [bitcoin-dot-org/Bitcoin.org#3431]
I'm going to experiment over the next few weeks with improving the buy page, you may see the page go through a few different iterations based on some different ideas.

Currently the page is not serving visitors well, there's no real call to action or purpose behind the page, and therefore a lot of visitors seem to just land on it and then subsequently don't engage properly with the content on the page. 

Ultimately the goal is to make the page as useful for its purpose as possible. The main thing is having more interactivity (for this page, and for more of the pages in general) -- rather than just presenting information. Also helps our search engine performance if users stay longer on certain pages.

**Comment by Cobra-Bitcoin** [comment]
Todos:

- Monitor visitor behaviour to see if a particular change drives engagement (undo the change otherwise)
- Some sort of A/B test?
- Re-arrange the page and experiment with showing the old information?
- Maybe remind users to set up a wallet before they investigate ways to buy Bitcoin?

**Comment by Daniel-Leedan** [comment]
Some suggestions:

- Add purchase fees information using the form on the page (4.5 % per transaction for debit/credit cards
1 % per transaction for bank transfers).
- Add a paragraph with information on other ways to buy Bitcoin (local exchanges, LocalBitcoin, etc.)
- Add a paragraph with some frequently asked questions for beginners before their first purchase.

**Comment by Lev-8** [comment]
Local Bitcoin

**Comment by mikehd2** [comment]
We suggested to Will Binns simplify this section in April 2020 by adding our project. And in May changelly implemented a convenient section for those who just want to buy bitcoin with a Bank card - changelly.com/buy - it is very convenient that you can choose a country and payment method, and it's uncomfortable that KYC must be passed everywhere. 
You can add multiple projects at once 
koinal.io 
banxa.com
itez.com
to simplify the purchase process for the user.

**Comment by pavlenex** [comment]
[I came across this research](https://www.useronboard.com/how-bitcoin-onboards-new-users/) which very well showcases how people had troubles with the buy page (though it's referring to the old design, but CTA's were the same on the newly designed site)

@Cobra-Bitcoin is this now ready to be closed as a result of the [a4bf3d69](https://github.com/bitcoin-dot-org/Bitcoin.org/commit/a4bf3d697aa9cf5050c6abe0d33b4fdae3bc5f25) or is it still part of the A/B test?

That said, I think current page servers people better than it did, but I'm not familiar with what [Moonpay](moonpay.io) is or how it works, or is it trusted, but perhaps that's type of experience  is what we want, would be good to add more diversity and the ability to maybe pick exchanges instead of relying on a single one in the future.

**Comment by Cobra-Bitcoin** [comment]
@pavlenex That research does a really good job showcasing the problem. People on the web are fickle, if you don't give them what they immediately expect when they search something, they leave, and Google takes that as a sign of a site being low quality and they penalize you. If we want to educate as many people about Bitcoin as we can, and have them avoid going to malicious alternatives, improving the performance of our pages is critical, otherwise we'd slide down the search results and end up with only a few thousand visitors instead of millions.

I'm still not 100% sure this will be the final version of the page, so we can keep this open to brainstorm future iterations. I also added a disclaimer to the page today under the widget based on someone's feedback on Reddit.

**Comment by real-or-random** [comment]
I wonder if this `api_key` leads to anyone getting money or other benefits from Moonpay. FWIW, the iframe seems to work without the `api _key`

**Comment by real-or-random** [comment]
> I wonder if this `api_key` leads to anyone getting money or other benefits from Moonpay. FWIW, the iframe seems to work without the `api _key`

@Cobra-Bitcoin Can you answer this? I assumed you obtained the API key, so you're probably the right person to answer.

**Comment by Cobra-Bitcoin** [comment]
@real-or-random I'm not the one that obtained the key, as that would require me providing personal information, but yes, there are small commissions which go toward covering some of the site's expenses.

It's possible to disable this, and not get anything though.

**Comment by real-or-random** [comment]
I believe then this should be stated more clearly on the site. I currently says "The above widget is provided by a third party provider (MoonPay) and is not associated with bitcoin.org.". Then in some sense, it is associated with bitcoin.org (even though not in a sense that you probably had in mind when writing this sentence)... I think it's a good policy to mark "affiliate" links (or widgets) as such.

For the record: I fully disagree with the decision to replace the buy page with a single widget, with and without commissions. I think it's harmful for Bitcoin because it means bitcoin.org is a not very neutral. Of course, this is a website maintained by humans and there must be some community-driven decision process behind it, and this can never be fully neutral and objective. But just offering a single option is the least neutral one can do, and also I don't see how this was a decision which is the result of any community-driven process, since the change was simply announced in https://github.com/bitcoin-dot-org/Bitcoin.org/issues/3431#issue-666517580. In anticipation that you won't agree with my criticism, I'm suggesting to change the at least the wording.

**Comment by Cobra-Bitcoin** [comment]
@real-or-random Bitcoin.org isn't Bitcoin, and replacing a barren page that gave users no option to actually buy bitcoin directly with one that does isn't "harming Bitcoin". If anything, it helps it, as people won't end up disappointed when they're trying to "buy bitcoin", as the research above showed.

Neutrality is a worthy goal to strive towards, and as much as a site can be neutral, it should be. In practise, however, that has ended up with people expecting to just use the site as a huge billboard, to plaster their services and links on, and to not give back any noteworthy contribution in return.

I'll change the wording though of the notice.
