### ISSUE TITLE
Linux Instructions > "Bitcoin Core download page"

### ISSUE THREAD

**Issue by dirtygardner** [bitcoin-dot-org/Bitcoin.org#3528]
Went to https://bitcoin.org/en/full-node#what-is-a-full-node

Side menu > "Edit On GitHub" https://github.com/bitcoin-dot-org/bitcoin.org/tree/master/en/full-node.md

Linux Instructions > "Bitcoin Core download page" [https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/en/download](https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/en/download) 
goes to "404: This is not the web page you are looking for."

**Comment by l33d4n** [comment]
Where did you find this link?

If you are looking for the source of this page: https://bitcoin.org/en/download
Check out this link: https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/_templates/download.html

**Comment by dirtygardner** [comment]
> Where did you find this link?
> 
> If you are looking for the source of this page: https://bitcoin.org/en/download
> Check out this link: https://github.com/bitcoin-dot-org/Bitcoin.org/blob/master/_templates/download.html

See edited first post.

**Comment by RandyMcMillan** [comment]
Github isn't case sensitive....I am creating a PR now to fix.

**Comment by RandyMcMillan** [comment]
@dirtygardner - Close if resolved.

**Comment by dirtygardner** [comment]
> @dirtygardner - Close if resolved.

Still goes to "404: This is not the web page you are looking for."

**Comment by amri1111** [comment]
https://github.com/amri1111/amri1111.git

**Comment by jdabs** [comment]
I see the issue. I believe @dirtygardner is speaking directly about the page as it appears on github dot com. Since the download links are relative (i.e. /en/download/), the links revert to using the root domain they appear on. Since the /download/ page is only bitcoin.org, they are expected to 404 on github .com url structure.

![image](https://user-images.githubusercontent.com/6774432/115162543-19882200-a072-11eb-92f0-4c71c23730f1.png)

**Comment by Cobra-Bitcoin** [comment]
I've opened a PR that fixes this. https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3647
