### ISSUE TITLE
More responsiveness/width-flexability in the devs-docs section

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-dot-org/bitcoin.org#723]
Reading the docs is pretty hard because the docs frame cannot be resized or anything like that.
It would be nice to have a option to view the docs in bar .MD (simple bootstrap css?).
Cool would be a option to fullscreen the page and toggle in/out the navigation.

Maybe this exists already.

This is how it looks on my screen.
![bildschirmfoto 2015-01-28 um 13 44 03](https://cloud.githubusercontent.com/assets/178464/5937841/e6224288-a6f4-11e4-9032-fca29399e21c.png)

**Comment by harding** [comment]
@jonasschnelli yeah, the layout in the API section is cramped with regard to the tables and code examples.  I think the rest of the docs, which is mostly paragraphs and images, works fine.

This leaves us something of a conundrum: I'd love to see the width increased (when screen sizes allow) for the API section, but I'd hate to see the width increased for the regular paragraph text.  (Studies show text lines with more than about 80 characters are hard to read.  Somewhere around 65 characters seems to be optimum.)

Maybe we could just tweak the current API layout to provide more space.  E.g. instead of using text descriptions for the "Type" and "Presence" fields, we could use icons with hover text.  For example, as seen below, instead of "number (int)", use ℤ, and instead of "Required (exactly 1)", use ☑.  The hover text would still have the full description.  This gives the "Description" field much more space.

![2015-01-28-090608_621x167_scrot](https://cloud.githubusercontent.com/assets/61096/5938892/217eacb8-a6cd-11e4-991a-63f779b47cfb.png)

For the example JSON output, it would be trivial to reflow the indentation tab stops to 2 spaces per stop rather than bitcoin-cli's default 4 spaces per stop.  That would provide a small but real condensation.
