### ISSUE TITLE
Update blockchain size on download page for Bitcoin Core

### ISSUE THREAD

**Issue by jlopp** [bitcoin-dot-org/bitcoin.org#749]
Trivial issue but we should probably update the note for the blockchain size because it's 50% larger now - from 20 GB to 30 GB.

**Comment by harding** [comment]
@jlopp agreed.  Thanks!  I'm probably going to update that note with a link when we merge the full node docs from pull #711, so if you think it's ok, I'll leave the way it is for now to prevent unnecessary re-translation.

**Comment by jlopp** [comment]
Sure; I looked at updating the translations and was able to change all but three of them - the Asian languages that don't use Latin numerals were the blocker :-P

**Comment by saivann** [comment]
Maybe we can only update it more or less when it doubles? Updating translations is indeed cumbersome, and I have no better trick than updating each translation by hand on Transifex, unfortunately. That's why I carefully wrote "*more* than 20GB" everywhere :) .

**Comment by jlopp** [comment]
Yeah there's not really a good way to automagically update it, plus this particular point will become even more complex when pruning lands in the 0.11 release...

**Comment by harding** [comment]
We could probably pop just the number out of the translation.  That'll work until we cross the GB/TB barrier.  I'm not a translation expert, but I expect arabic numerals are understood by anyone using a computer (as well as anyone using a Bitcoin client---I'm pretty sure Bitcoin Core itself uses arabic numerals for bitcoin balances in all languages).

**Comment by saivann** [comment]
@jlopp Oh, indeed!

@harding I'm not sure I am following you; removing the number from translations would require translators to re-translate the strings, while just changing the number can be done without any prior knowledge for said languages in most cases. And in either case, since it says "more than 20GB", it should remain accurate if some translations cannot be updated for some reason.

**Comment by harding** [comment]
@saivann two things:

1. I was thinking we should probably change that string to point to the full node guide when we release it.  That will trigger a re-translate anyway.  Thanks to @jlopp for pointing out the future pruning---when I rephrase to mention the full node guide, I can also try to make sure the phrasing will work for when pruning becomes an option.

2. If we remove the actual number from the string (replacing it with a single numeric variable set somewhere else), then we can change the number easily in the future without worrying about translations.

Also, I'm happy you said more than 20GB because it means this isn't an urgent issue. :-)

**Comment by saivann** [comment]
@harding Ah, right! That all sounds good, thanks! :)

**Comment by harding** [comment]
Note, I decided not to mess with the current text at all.  I couldn't think of a clever way to re-phrase the three occurrences of 20GB in _translations/en.yml in a way that would be easy to update in the future and also work with pruning.  Since pruning is (hopefully) only about 6 months off (and the current text is still accurate), I think we should just do a complete rewrite then.

I'm leaving this issue open so I don't forget.  Thanks again @jlopp for reporting this!
