### ISSUE TITLE
More clearly encourage running a full node

### ISSUE THREAD

**Issue by luke-jr** [bitcoin-dot-org/bitcoin.org#882]
Perhaps in addition to the choose-a-wallet page (above the "lists"?) there should be a note about how one should run Bitcoin Core even if they use another wallet.

**Comment by coderwill** [comment]
Hi @luke-jr - what's the URL for the page you're talking about?

**Comment by harding** [comment]
@luke-jr do you mean (1) running Bitcoin Core so that your SPV wallets can connect to it, or (2) running Bitcoin Core to relay blocks and txes to other nodes and clients?

If (1), then I've already been working on that in a branch that does (I hope) a better job of promoting Bitcoin Core.  A screenshot of the current draft UI page is attached below.  I prefer not to receive feedback on the page until I'm finished with it.

If (2), then we already link to the [full node guide](https://bitcoin.org/en/full-node) from every page on the site via the Participate menu on the top of each page.

If there's a third reason people should run Bitcoin Core even if they use another wallet, I'd love to hear it so I can help promote it.

![screenshot-btcorg localhost 2015-06-10 13-17-31](https://cloud.githubusercontent.com/assets/61096/8089225/8c98f11a-0f74-11e5-9114-7d1b8a4a8a7f.png)
